python/Ganga/Core/__init__.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/GPIDev/Lib/Tasks/ITransform.py
python/Ganga/GPIDev/Lib/Tasks/TaskApplication.py
python/Ganga/Lib/Executable/Executable.py
python/Ganga/Lib/LCG/LCG.py
python/Ganga/Lib/LCG/LCGRequirements.py
python/Ganga/Lib/Localhost/Localhost.py
python/Ganga/Lib/Root/Root.py

I've made a few small cleanups to the code which I hope are uncontroversial. This is mostly so that everyone can see what a pull request looks like and practice with commenting and doing the code review.
Once everyone is happy, then we can accept it and make sure that is working.
We don't have any automated checking of pull requests yet but that will be coming in the future.

Some small cleanups

---

python/GangaLHCb/Lib/RTHandlers/LHCbGaudiDiracRunTimeHandler.py

minor typo

---

python/GangaPanda/Lib/Athena/AthenaJediRTHandler.py

Enabled the mergeScript option in Jedi

---

python/Ganga/Core/__init__.py
python/Ganga/GPIDev/Lib/Registry/BoxRegistry.py
python/Ganga/Utility/ColourText.py

This is a retry of PR #8 with the change that @rob-c suggested.

Remove unreachable code

---

python/Ganga/GPIDev/Lib/File/MassStorageFile.py
python/Ganga/GPIDev/Lib/Tasks/Task.py
python/Ganga/Lib/Batch/Batch.py
python/Ganga/Lib/Condor/Condor.py
python/Ganga/Lib/Interactive/Interactive.py
python/GangaLHCb/Lib/Tasks/LHCbTask.py

Fixing some problems found by @chrisburr in testing https://github.com/ganga-devs/ganga/pull/62

Add missing imports and fix misnamed attribute

---

python/Ganga/PACKAGE.py

This is to try and address #86

Removing pycryo and paramiko from Core externals for the time being

---

python/GangaLHCb/Lib/Tasks/LHCbAnalysisTransform.py

Fixing GangaLHCb not loading due to GangaLHCb tasks after Config changes

Fixing Problems due to Config change

---

.gitignore
doc/GPI/index.rst
doc/dev/index.rst
doc/fill_gpi.py
doc/index.rst

This is just some minor documentation improvements for Sphinx. It adds two main things, a list of the exported GPI functions and a preliminary version of a Ganga developer's guide detailing some of the larger internal details of the code base.
In general I welcome any additions people wish to make to the dev guide and the other pages too.

Doc improvements

---

python/Ganga/Core/FileWorkspace.py
python/Ganga/GPIDev/Adapters/StandardJobConfig.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/GPIDev/Lib/Registry/JobRegistry.py
python/Ganga/Lib/LCG/GridShell.py
python/Ganga/Runtime/bootstrap.py

This is hopefully a completely safe PR as it only removes things that have been deprecated or not working for many years (since at least 2010). They have all had deprecation warnings printed and many aren't even user-reachable.

Remove deprecated funtions etc.

---

python/Ganga/GPIDev/Schema/Schema.py
python/Ganga/Utility/Config/Config.py
python/GangaTest/Framework/__init__.py

This fixes #92 by stopping `_getDefaultValueInternal` from creating config sections.

Fix default config loading

---

python/Ganga/GPIDev/Lib/Job/Job.py

Some simple PEP8ing of Job.py to reduce the trivial static analysis warning this file produces. The imports were extracted to module scope manually and then sorted using [isort](https://pypi.python.org/pypi/isort) which does a good job of keeping things neat.

Job.py: Reorganise imports and some PEP8ing

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Base/Proxy.py
python/Ganga/GPIDev/Lib/GangaList/GangaList.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/test/GPI/GangaList/TestCopy.py
python/Ganga/test/GPI/GangaList/TestGangaList.py
python/Ganga/test/GPI/Resubmit.gpi
python/Ganga/test/GPI/WorkspaceRemoval.ini
python/Ganga/test/Internals/TestRegistry.gpim
python/Ganga/test/Performance/PerfStats.gpim
python/Ganga/test/Performance/PerfStats.ini

I've fixed some bugs I came across in testing ahead of 6.1.15.
This includes some fixes into GangaList, Proxy and the Registry.

Bugfix/fixing bugs in 6.1.15 testing

---

python/Ganga/new_tests/GPI/Loading/TestLazyLoading.py
python/Ganga/new_tests/GPI/Loading/testLazyLoading.py
python/Ganga/new_tests/GPI/Parser/TestParser.py
python/Ganga/new_tests/GPI/Parser/testParser.py
setup.py

This should be enough to get some outstanding unittests to work with Jenkins.

Moving tests and attempting to get them to run with Jenkins

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py

Fixing bug in XML repo found in testing

Fixing api bug

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

When stopping and restarting the monitoring, some jobs were not being
monitored as the system had stale data claiming that they were already
covered and so no new monitoring should be performed.
By making updateDict_ts a member of the JobRegistry_Monitor class it will
be recreated every time the monitoring is started and so will recheck
everything.

Make updateDict_ts so that it's recreated each time

---

python/Ganga/Core/InternalServices/Coordinator.py
python/Ganga/Runtime/Repository_runtime.py
python/Ganga/Runtime/Workspace_runtime.py
python/Ganga/Runtime/bootstrap.py
python/ganga/__init__.py

These are some minor changes which should have no actual effect on any code. It is just removing code which is not needed in a long time.

Minor bootstrap tidy

---

python/Ganga/new_tests/GPI/Parser/TestSelect.py

A new test to check for #253. Accidentally based this on #179 so will rebase after that has finished.
This replaces #255 where I forgot to add the test anyway... ooops

Adding jobs.select test

---

python/ganga/__init__.py

Very minor change to avoid errors to do with objects not having the '_proxyClass' member.

Changed little ganga to use getProxyClass(cls) to avoid error

---

python/Ganga/Core/GangaRepository/GangaRepository.py
python/Ganga/Core/GangaThread/WorkerThreads/ThreadPoolQueueMonitor.py
python/Ganga/Core/GangaThread/WorkerThreads/__init__.py
python/Ganga/Core/InternalServices/Coordinator.py
python/Ganga/Core/InternalServices/ShutdownManager.py

OK, 3rd time lucky, (Apologies for the spam)
I'm new to cross-branch pull-requests and would have preferred to stick this in develop myself and resync the release branch.
This should address #285
If there are questions feel free to ask.

Making sure 'join' is called on all stopped queues before the end

---

python/Ganga/Core/GangaRepository/SessionLock.py
python/Ganga/Runtime/Repository_runtime.py

Fixing SessionLock errors

---

python/Ganga/Core/GangaRepository/VStreamer.py

Try for fix for the parent not being set in SJID test. If this works I'll update this.

Trying to fix issue with lists and parents

---

python/Ganga/Core/GangaThread/WorkerThreads/__init__.py

The 1 line to fix the annoyance from shutting down queues For sake of waiting I'll wait for the tests to finish then push.

Fix queue shutdown

---

python/Ganga/GPIDev/Adapters/ISplitter.py

Resetting the value of the `inputdata` parameter here to a list is incorrect as `inputdata` is not a sequence but rather a `ComponentItem` with a `defvalue` of `None`.

j.inputdata is a 'datasets', not a sequence

---

python/Ganga/new_tests/GPI/newXMLTest/TestSJXMLGenAndLoad.py

Fixing test which fails occasionally due to transitioning state.
This may itself fail as a fix if the test is inconsistent but I hope to find out in testing now.

Fixing test

---

python/Ganga/GPIDev/Lib/Registry/RegistrySlice.py
python/Ganga/new_tests/GPI/Parser/TestSelect.py

This fixes #350 and adds some more detailed tests to better check that ```jobs.select``` doesn't break again in the future without us noticing.

Fix select

---

python/Ganga/Core/InternalServices/ShutdownManager.py
python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py
python/Ganga/new_tests/GPI/Tasks/TestCoreTasks.py

This should fix the Tasks lockup seen in the testing. However, I can't recreate this locally so I guess we'll have to wait and see...

Fix tasks lockup

---

python/Ganga/Core/GangaRepository/Registry.py

Search registry by identity in find()

---

python/Ganga/GPIDev/Lib/Registry/RegistrySlice.py
python/GangaLHCb/Lib/RTHandlers/RTHUtils.py
python/GangaLHCb/Lib/Tasks/LHCbUnit.py

- Fix typo of debug function.
- Make Tasks work again.
- Re-add change that got lost somewhere allowing Tasks using GaussSplitter to seed the event number properly.

Trivial bugfixes

---

python/GangaDirac/Lib/Backends/DiracBase.py

Move break and comment lines around

Move break and comment around

---

python/Ganga/GPIDev/Base/Proxy.py

This is a version of #451 which works for my original problem.
I was running a short test against #451 which seemed to indicate that it was working, however it failed to fix the problem that prompted me to write the PR.
I'll merge after the tests have patched as this isn't anything which hasn't been seen before.

Reverting to setNodeAttr as setattr doesn't work for all cases

---

python/Ganga/GPIDev/Lib/Dataset/GangaDataset.py
python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

I think this fixes #480, either way this is now not the correct behaviour of the code.
I'd like to merge this, then test #477 to see if this fixes it.

Stop the Datasets from adding proxies which aren't needed

---

python/Ganga/GPIDev/Lib/Dataset/GangaDataset.py

This PR just adjust the exposed methods in the ```GangaDataset``` to allow it to be used more easily.
Does anyone feel I should expose other functions should I expose as part of this? (I'm happy to expand the list)
This isn't 100% essential but I would like to use the object with LSST code as in #471.

Minor changes to GangaDataset to allow it to be manipulated

---

python/Ganga/Lib/Condor/Condor.py

Fix issue with IndexError monitoring a Condor Job

---

python/GangaPanda/Lib/ProdTrans/ProdTransPandaRTHandler.py

The transfertype is now taken into account when submitting ProdTrans jobs for HC.

Added transfertype to ProdTrans RT Handler

---

python/Ganga/Core/GangaRepository/SessionLock.py

It was found in #463 that if you run Ganga on an FS without file locks, it hangs. I'm not sure of the exact reason for this but I'm assuming it's to do with the `delay_lock_mod` function which attempts to lock a file many times. In theory, this should fail eventually but that doesn't seem to be what's happening. Looking at the `fcntl` docs and what happened when running the `fcntl.lockf` function in plain python, if it can't acquire a lock straight away then it doesn't seem necessary to keep trying as it probably will never acquire a lock. 
The testing works on my machine and so I believe this to be safe. Let me know if not!
Fixes #465

Removed delay_lock_mod function which hung on no filelock FS

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/Core/InternalServices/ShutdownManager.py
python/Ganga/Core/__init__.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/Runtime/bootstrap.py
python/ganga/__init__.py

This is another version of #510 without the horrible mess while I was tracking down a couple of lockups.

Cleanup atexit handling (cleaned version)

---

python/GangaPanda/Lib/Athena/AthenaPandaRTHandler.py
python/GangaPanda/Lib/Panda/PandaRequirements.py
python/GangaPanda/Lib/ProdTrans/ProdTransPandaRTHandler.py

Add specialHandling option to PandaRequirements for HC

---

python/GangaND280/ND280Checkers/ND280Checker.py
python/GangaND280/ND280Control/ND280Configs.py
python/GangaND280/ND280Control/__init__.py
python/GangaND280/ND280Control/runND280SandMC.py
python/GangaND280/doc/mainpage.dox
python/GangaND280/examples/tskSandMC.gpi

update GangaND280 to nd280Ganga CMT as of 2016.06.06 10:21 UTC

---

python/GangaLHCb/ganga-proxy.py

Just a minor code cleanup addressing #566 
Fixing #566

Cleanup proxy code

---

python/Ganga/testlib/GangaUnitTest.py

Make the code that is run to set up Ganga on each test run as similar as possible. This fixes the config being reset so aggressively between tests and moves the code to being more similar to a standard run of the `ganga` application.

Reduce the difference between test run setups

---

python/GangaLHCb/__init__.py

Migrating the LHCb config to make use of `setSessionValue` rather than `overrideDefaultValue`. Will play nicer with tests etc and cleans things up a little.
Nothing major changes so I'll merge this after the tests finish

Cleaned config

---

python/GangaDirac/Lib/Files/DiracFile.py

Superseding #559 as the test that defaultSE is in a list of all known SE is not really valid

Minor cleanup of DIRACFile

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py

This PR is an attempt to make the OfflineSplitter for DIRAC slightly more robust and correctly handle some external call failing for some reason.
I've also cleaned up the imports a little.

Some splitter improvements

---

doc/UserGuide/InstallAndBasicUsage.rst

adding some extra docs for users
Adding some extra docs to get provide users with different ways of installing Ganga and a quick set of instructions to show them how to switch to develop if they're advised to do so.

Adding some extra docs

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py

Minor change of use of dict

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py

1 line fix of rmrf

---

python/GangaLHCb/Lib/GaudiRunApp/PythonOptsCmakeParser.py

removing dupicate function from GaudiRun code

removing duplicate function

---

python/GangaLHCb/Lib/Applications/AppsBase.py

Fixing bug in nightly due to import

---

python/Ganga/test/GPI/TestSJSubmit.py

Adding docs/asserts

---

python/Ganga/GPIDev/Lib/File/OutputFileManager.py

It seems that the merge of #493 didn't make it into develop from master after the release so I'm just re-applying this fix directly.

Fix broken import in WN script

---

release/tools/afs_test_install/install-from-github
release/tools/afs_test_install/test-from-github

Adding the tools on AFS used in the release procedure

Add afs tools

---

python/GangaDirac/Dirac.ini

Setting ReleaseNotes = True
Fixes #676

Setting ReleaseNotes = True

---

python/Ganga/Core/Sandbox/Sandbox.py
python/Ganga/GPIDev/Lib/File/LocalFile.py
python/Ganga/Lib/Localhost/LocalHostExec.py

This is some minor code cleanup and fixing a minor bug in LocalFile.
I'm planning to merge this tomorrow unless there are any objections

Code cleanup and LocalFile construction fix

---

python/Ganga/GPIDev/Lib/File/File.py

This PR just changes the logging level so users don't have to worry about a folder being created for them.

Update File.py to make sharedir silently

---

python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

This PR deletes the local files generated during the submission of a CMake job to the grid to reduce the files left on disk.
I'm exploring removing the shared directory when it's no longer needed locally but this will be in another PR as I need to download missing files again if we copy a prepared job and run it on a Local/Batch machine vs Dirac.

Cleaning up local files after they've been uploaded to Dirac

---

release/ReleaseNotes

Please take a look and add in anything that is missing/correct anything wrong. I'll release in an hour or two if there are no objections.

Update ReleaseNotes for 6.1.23

---

python/GangaPanda/Lib/Athena/AthenaPandaRTHandler.py

Athena releases 21+ use CMake instead of CMT and this allow Hammercloud tests to run with this.

Add --useCMake flag and bump the runAthena version

---

release/ReleaseNotes

Update release notes for 6.1.25

---

python/GangaLHCb/Lib/Applications/GaudiExec.py

Let me know if there are any issues with this fix.
Fixes #749

Fix small mistake in help string, fix issue #749

---

setup.cfg

Updating based upon warnings from Jenkins box

Updating setup.cfg

---

python/GangaDirac/test/Unit/DiracAPI/TestDiracCommands.py

Otherwise the hard-coded SE could be down and cause a false negative. This is an alternative fix for #772

Fix DIRAC test by trying each SE in order until one works

---

python/GangaDirac/test/Unit/DiracAPI/TestDiracCommands.py

Don't continue DIRAC test if we're returned an empty dictionary

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

This is a really small fix to fix a coding bug introduced by accident at some point into the monitoring code. (string doesn't know about append)

Minor monitoring fix

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/Core/GangaRepository/SessionLock.py

Reverts ganga-devs/ganga#785
Reverts the changes to SessionLock for now. I'll merge after the tests run.

Revert "Cleanup xml/sessionlock implementation"

---

python/GangaLHCb/Lib/RTHandlers/LHCbGaudiDiracRunTimeHandler.py
python/GangaLHCb/Lib/RTHandlers/LHCbGaudiRunTimeHandler.py

This fixes #140 
If it can make it to 6.2.1 I would be very happy.

Fix old LHCb RT handlers to propagate parsed xml summary

---

python/GangaLHCb/Lib/Applications/GaudiExec.py

This fixes some display issues with the GaudiExec app. The defaults were bad, but not too harmful.

Fixing defaults in GaudiExec

---

python/GangaLHCb/__init__.py

Updating the LHCbDirac version

Change default LHCbDirac version to v8r3p7

---

python/GangaLHCb/__init__.py

The latest LHCb code is not safe for me and bails out in a bad way.
I've updated the code and I think this needs integrating into 6.2.1.

Fixing LHCb init code

---

python/Ganga/__init__.py
python/GangaDirac/Lib/RTHandlers/DiracRTHUtils.py
python/GangaLHCb/Lib/Applications/GaudiExec.py

I think this fixes the problem #830  - could someone else check. I also fixed something in the DiracRTHUtils.

A fix for the thread lock in the GaudiExec prepare

---

python/GangaLHCb/Lib/Applications/GaudiExec.py
python/GangaLHCb/Lib/Applications/GaudiExecUtils.py
python/GangaLHCb/Lib/Applications/PythonOptsCmakeParser.py
python/GangaLHCb/test/GPI/TestExternalGaudiExec.py

Fixes #841 
@mesmith75 Can you test this PR as this should fix the problems with `readInputData`.

Fixing bug in opts parser for GaudiExec

---

python/GangaLHCb/__init__.py

Just updating LHCbDirac. This version has a bugfix for the bookkeeping. #835

Update LHCbDirac to v8r3p10

---

python/GangaLHCb/Lib/Splitters/GaussSplitter.py

Fixes #840. Quick fix for the number of events in GaussSplitter for GaudiExec.

Fix for GaussSplitter with GaudiExec

---

python/Ganga/GPIDev/Credentials/VomsProxy.py
python/Ganga/test/GPI/LCG/TestCREAM.py
python/Ganga/test/GPI/LCG/TestLCG.py
python/Ganga/testlib/GangaUnitTest.py
python/Ganga/testlib/mark.py

This is an attempt to fix the `6.3-features` branch tests given the recent changes.

Adding a minimal Credential checking Decorator

---

python/Ganga/Lib/Batch/Batch.py
python/Ganga/Lib/Batch/BatchScriptTemplate.py.template

Make inputdata files available on Batch backends

---

python/Ganga/Lib/Batch/BatchScriptTemplate.py.template

Fix typo in Batch backend template script

---

python/GangaLHCb/Lib/Applications/EnvironFunctions.py

Fix prepare of old LHCb applications with new login scripts

---

python/Ganga/test/GPI/Credentials/TestCredentials.py

Potentially fixes #882 I don't know if we _want_ these external but in my mind they should be as they rely on commands/servers outside of Ganga.

Nightly Cred req fix

---

python/GangaLHCb/Lib/Applications/GaudiExecUtils.py
python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

Fixes #886 . For the prepare_cmake function.
Check whether the Dev folder already exists. If it does, raise a GangaException rather than continuing with the job submission.

Cmake folder exception exception

---

python/GangaLHCb/test/GPI/TestDatasets.py

Fixes #857 . Added some tests for the LHCbDataset functions - separated from those that require externals.

Local LHCbDataset tests

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/Utility/Runtime.py
python/GangaLHCb/Lib/Backends/Dirac.py
python/GangaSuperB/Lib/SBApp.py
python/GangaSuperB/Lib/SBInputDataset.py
python/GangaSuperB/Lib/SBOutputDataset.py

This commit addresses issues raise in the review of
https://github.com/ganga-devs/ganga/pull/752
modified:   python/Ganga/Core/GangaRepository/Registry.py
modified:   python/Ganga/Utility/Runtime.py
modified:   python/GangaLHCb/Lib/Backends/Dirac.py
modified:   python/GangaSuperB/Lib/SBApp.py
modified:   python/GangaSuperB/Lib/SBInputDataset.py
modified:   python/GangaSuperB/Lib/SBOutputDataset.py

Combine Ganga exception imports and remove unnecessary raise.

---

release/ReleaseNotes

6.3.1 ReleaseNotes

---

python/Ganga/Core/GangaRepository/FixedLock.py
python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/testlib/GangaUnitTest.py

This is a short PR to investigate what the effect of changing some configurables has on the speed of the integration tests.

Test changes

---

python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

This fixes #933 (I think) and addresses my concern about known exceptions NOT causing a stack trace as this is not what we're intending to do.
Feel free to modify/edit this PR but this should be reasonably clear as to what I'm aiming for.

Cleaning up exceptions

---

python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/test/GPI/TestSubjobs.py

Fix for killing jobs and subjobs

---

python/GangaDirac/Lib/Backends/DiracBase.py

Fix for Dirac getOutputDataAccessURls

---

python/Ganga/Core/GangaRepository/SessionLock.py

Better compatibility with NFSv4.

Try to change the lock files to be opened in read/write mode to have

---

release/ReleaseNotes

Release notes - 6.5.0

---

python/Ganga/GPIDev/Lib/File/File.py
python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py
python/Ganga/test/GPI/TestShared.py
python/GangaLHCb/Lib/Applications/BenderBox.py

This PR touches the `ShareDir` class and does 2 things:
1) Fixed the mis-use of the `._name` attr -> `._real_name`
2) Added a global and schema based setter to handle storing the persisted values from XML better
As always feel free to fix/modify but this should address (at least some of) the problems correctly highlighted in #980 .

Fixing ShareDir persistency... schema should support setters

---

python/GangaLHCb/Lib/Applications/GaudiExecUtils.py

Fixes #954. Also added a check and exception raise for if the lb-dev folder was created.

Change getpack to git lb-checkout for prepareGaudiExec

---

python/GangaDirac/Lib/Files/DiracFile.py

Add replica check in getMetadata

---

python/GangaLHCb/Lib/Applications/GaudiExec.py

Fix GaudiExec extraArgs

---

python/GangaDirac/Lib/Backends/DiracUtils.py
python/GangaDirac/Lib/Server/DiracCommands.py
python/GangaDirac/Lib/Server/DiracDefinition.py
python/GangaLHCb/Lib/Server/DiracLHCbCommands.py
python/GangaLHCb/Lib/Server/DiracLHCbDefinition.py

Fixes #984 . I need to add some nightly tests for this for regular Dirac and LHCb Dirac.

Set root/xroot default protocol for LHCb

---

python/Ganga/GPIDev/Lib/Config/Config.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/Config/Config.py

Fixes #998 
I added the gangarc set of option values and updated the code that updates/generates a new gangarc to only use those.

New config fix

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py
python/Ganga/GPIDev/Lib/Job/Job.py

Applying this locally appears to fix the issue described in #327.

Fix auto resubmission #327

---

python/GangaLHCb/Lib/Applications/GaudiExec.py

GaudiExec is_prepared after succesful build

---

release/ReleaseNotes

Please take a look at the explanation for the config bugfix.

Release notes for 6.5.2

---

python/Ganga/Dockerfile
python/GangaDirac/Dockerfile

Add a base docker image for GangaCore and build the GangaDirac image from it.

Add GangaCore Dockerfile.

---

python/Ganga/GPIDev/Lib/File/MassStorageFile.py

Add GangaException import to MassStorageFile

---

python/Ganga/GPIDev/Adapters/ISplitter.py
python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

Fixes #1005 . Also a minor bugfix in LHCbDataset.

SplittingError to GangaException

---

python/GangaDirac/Lib/Utilities/DiracUtilities.py
python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

Fixes #897 . This adds an optional id to the GangaDiracError. Not sure how useful this really is as there doesn't seem any obvious place at the moment where it is needed.
Also removed unused import in LHCbDataset.

Add optional id to GangaDiracError

---

python/Ganga/GPIDev/Lib/Config/Config.py

Changes from no to yes for future versions.

Change the default when making new gangarc

---

python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

Add two extra RT handles to GaudiExec.

add PBS and SGE to GaudiExec RT handlers

---

python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/PACKAGE.py
python/GangaPanda/Lib/Jedi/Jedi.py

Update the rucio version and use the correct path. This should sort out getting Atlas working on SL7.
I've also put in another minor fix for a non-assigned variable and removed some broken new credential code until I get a chance to fix it properly.

Get Atlas working on SL7/Centos 7

---

python/GangaAtlas/Lib/ATLASDataset/ATLASDataset.py
python/GangaAtlas/Lib/ATLASDataset/__init__.py
python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/Lib/Athena/AthenaLCGRTHandler.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/scripts/athena

More Atlas detritus for removal 😄

Remove ATLASDataset class

---

python/GangaLHCb/Lib/Applications/BenderBox.py
python/GangaLHCb/Lib/Applications/BenderScript.py
python/GangaLHCb/Lib/Applications/GaudiExec.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

Fixes #1042. Added in the XML summary for the BenderBox apps.
Also fixes a bug that the summary script wasn't going into a reasonable place.

Add metadata to BenderBox

---

python/Ganga/__init__.py

Added the various batch backends into configuration. In the longer term some default action might be preferable to define.

Updated configuration on where output files should be treated

---

release/ReleaseNotes

Take a look and if you are happy approve them.

Release notes for 6.6.4

---

python/GangaLHCb/Lib/Applications/GaudiExec.py

Make XML postprocessor optional in GaudiExec

---

python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

Remove script files from tmp in GaudiExec

---

python/GangaDirac/Lib/Files/downloadScript.py.template
python/GangaDirac/Lib/Files/uploadScript.py.template

Fix uploadScript template

---

python/Ganga/Lib/Splitters/ArgSplitter.py

Add check for GaudiExec schema in ArgSplitter

---

python/GangaAtlas/Lib/ATLASDataset/DQ2Dataset.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/run-athena-new.sh

This provides support for BYTESTREAM jobs in Atlas

Add bytestream support

---

python/Ganga/GPIDev/Lib/Tasks/ITransform.py

Fixes bug where transforms cannot continue on from one another in a task (as discussed with @drmarkwslater)

Modified order of creating units and checking if units exist.

---

python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

Add GangaException import for GaudiExec RTHandler

---

python/Ganga/Lib/LCG/Grid.py

Fix arcsync

---

python/GangaDirac/Lib/Backends/DiracBase.py

Block submit fix

---

python/GangaDirac/Lib/Files/DiracFile.py
python/GangaDirac/Lib/Utilities/DiracUtilities.py

Added a check that the result of the put is a dict - if not raise an exception. This seems to be where issues creep in if Dirac things are going awry so it would be nice to get the output properly.

Return Exception if call to Dirac API is not returning a dictionary

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/__init__.py
setup.py

Some modifications to prevent starting ganga when running the setup script. Also adds a DEV tag.

Improve version for installation

---

python/GangaDirac/Lib/Backends/DiracBase.py

Dirac auto_resubmit fix

---

python/GangaDirac/Lib/Files/DiracFile.py
python/GangaLHCb/Lib/Applications/GaudiExec.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

Fixes #1133 
Also remove replicas in the postprocessor.

Replicate GaudiExec files

---

python/Ganga/GPIDev/Adapters/IBackend.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/Lib/Interactive/Interactive.py
python/Ganga/test/GPI/Bugs/TestSavannah17080.py

Seems worthwhile setting this to True by default.
Do we want to change the default in the `IBackend` as well?

Set parallel_submit to True by default in job
