python/Ganga/Runtime/bootstrap.py

Due to an mistake on my part when converting the version strings for Git (trying to use 'x.y.z' consistently everywhere rather than 'Ganga-x-y-z') it now breaks to run 6.1.11 and then go back and run 6.0.44 (for example). This is because the new_user_wizard runs and regenerates the config and places:
on the first line which, when read by 6.0.44, fails to do a `version.split('-')[1]` on it and crashes.
Since we can't go back and change 6.0.44 etc. we need to make sure the config file from 6.1.12 can be read by earlier versions.
@rob-c did warn me about changing this version code but I thought I'd caught all the issues. However, this one slipped through.

Fix backward-compatibility for config versions

---

python/Ganga/Runtime/bootstrap.py

Initialising the IPython InteractiveShellEmbed under IPython 2.3.1(python 2.7.9) complains of unexpected keyword so I bump the compatibility fallback for IPython2
The traceback I see is as below:
```python
Traceback (most recent call last):                                                                                 
File "bin/ganga", line 64, in <module>                                                                           
Ganga.Runtime._prog.run()                                                                                      
File "/home/hep/arichard/git/ganga/python/Ganga/Runtime/bootstrap.py", line 1346, in run                         
self.launch_IPython(local_ns, args, self._ganga_error_handler, self.ganga_prompt)                              
File …
```

Fix initialisation of IPython2 interactive shell

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

When trying to get the new test system running in non-interactive mode (i.e. no active monitoring loop) I came across a race condition where a thread acquires a lock but never releases it. I wanted to check that this was a bug and not a feature that's malfunctioning elsewhere.
The lock is acquired on line 297 and is released on line 305 in the `if` block. However, in the `else` block it is never released and the function then returns, holding the lock forever.
I'd rather have changed this to a context manager but it's not possible to acquire a non-blocking `RLock` using a context manager.
@alexanderrichards, @rob-c Since you've been looking at the monitoring code before, perhaps you have a better idea?

Make sure lock is released in monitoring

---

python/Ganga/Runtime/bootstrap.py

Just a small branch to expand the paths within the RUNTIME_PATH so that user extensions will be loaded correctly without the user having to give the explicit full path to their extension.

Auto-expanding variables and user tilde for RUNTIME_PATH

---

python/GangaAtlas/Lib/Tasks/AnaTask.py
python/GangaAtlas/Lib/Tasks/MCTask.py
python/GangaAtlas/Lib/Tasks/MCTransforms.py
python/GangaAtlas/Lib/Tasks/MultiTask.py
python/GangaAtlas/Lib/Tasks/MultiTransform.py

Fixes #103. Note that all these files can really be removed in the long term as they are obsolete.

Fix atlas task import after config

---

python/Ganga/Utility/files.py

logging.DEBUG does not exist in our logging module and so this was causing
an exception. It wasn't really needed anyway so it has been removed from
here.
Without this, doing
```python
File('x')
```
would crash on latest `develop`.

Simplify logging in file utilities

---

python/Ganga/GPIDev/Base/VPrinter.py

While `quoteValue()` handles multiline strings if they are by themselves, it fails if the string is inside a `list` or `GangaList`. This simplifies the logic of `quoteValue` by using `repr` for the string quoting behaviour and handing iterables manually.
This fixes the failure in Savannah13979.

Fix VPrinter's quoting so that it handles multiline strings in lists

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/GPIDev/Lib/GangaList/GangaList.py
python/Ganga/GPIDev/Lib/Job/Job.py

Hi all,
After removing the extra load statements from the Registry commands I discovered an odd bug in the Jobs class which took a short while to solve.
When a Job containing subjobs was read from disk all of the information and parent knowledge was setup correctly for the objects created based upon the XML.
However, I discovered that once the subjobs are allocated within the Job class they have no immediate knowledge of their parent until the job is re-loaded from disk.
I've made a generic fix now such that when a subjob is added to job.subjobs the knowledge of the parent job is preserved. Hopefully this should prevent the strange oddities I was seeing from creeping up again.
This problem has only come to light now as the flushing is correctly delayed until the job is marked 'dirty …

Bugfix/fixing fqid bug/Subjobs not having Parent knowledge bug

---

python/Ganga/GPIDev/Base/Proxy.py

Currently, when a `GangaObject` is proxy-wrapped, its `__doc__` attribute is reset to a generic string pointing the reader towards the proxy object. In the process of auto-generating API and GPI docs, this is getting in the way.
Does anyone have a objection to removing this? I don't see that it adds any value.

Don't overwrite the existing documentation for a proxied GangaObject

---

python/Ganga/Runtime/bootstrap.py

Previously environment variables were not expanded, resulting in the GangaRootPath being prepended to paths beginning with an environment variable.

Fix to expend environment variables in RUNTIME_PATH.

---

python/Ganga/GPIDev/Base/Objects.py

This is a cleanup exercise in `Descriptor.__get__`. The code before was overly nested as well as calling lots of functions it did not need to. The logic in these functions should be clean and easy to follow and hopefully this is getting there now.
I've noticed some speed-ups in XML loading with this as well.

Simplify descriptor get

---

python/Ganga/GPIDev/Lib/File/GoogleFile.py

The GoogleFile Client ganga developer account didn't have the Drive API enabled. Clearly something at Google has changed as it used to work and therefore must have had it enabled at some point. Since I don't remember the password anymore to this account I have generated a drive enabled API credential against my work gmail account and used the credential in this fix to get things working again. Ultimately we should re-do the credential with the ganga developer account.

Fix the GoogleFile Client

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Base/Proxy.py
python/Ganga/GPIDev/Base/__init__.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/GPIDev/Lib/Job/__init__.py
python/Ganga/new_tests/TestGangaObject.py

Mostly this is just moving some code from `ObjectMetaclass.__init__` into `GPIProxyClassFactory` since it is only relevant to proxies.

Cleanup ObjectMetaclass

---

python/Ganga/GPIDev/Adapters/IBackend.py
python/Ganga/new_tests/GPI/TestArgSplitter.py

Running a simple job like seen in TestArgSplitter.py was failing with errors. This fixes them.
@rob-c The only question I have is that `j.subjobs` is a `GangaList` by line 487; I forget if that is expected at this point?

Fix splitter

---

python/Ganga/Runtime/bootstrap.py

I use multiple .gangarc (so that I can specify different ganga directories to separate workflows).  Moving to the latest develop version of ganga I cannot start ganga as no versions file exists.  Maybe there's a reason for not creating a new versions file if a custom config file is specified, in which case a different fix is needed.

always create a versions file if one does not exist

---

python/Ganga/GPIDev/Lib/Job/Job.py

Commit [320e247e1ad](https://github.com/ganga-devs/ganga/commit/320e247e1add935c09dfe3dede1b87e305f4ce66#diff-7056ed3fcb714dad4d540fcd686efe61R403) changed the behaviour of `j.status` so that it was *always* preferring the index cache (if present) over the real data, even if there was real data present and so was presenting stale information. This is what's been causing a lot of the problems of jobs 'reverting' to `submitted` when they should be `running` or `completed` etc. (at least as far as my testing can see).
The check for the index cache is done in `Descriptor.__get__` anyway so this shouldn't cause full loading.
In discussion with Mark we agreed that there shouldn't be any cases where the index cache is populated on a fully-loaded job, especially one that's only just been created …

This reverts 320e247e1ad which was causing stale data to be displayed

---

python/Ganga/Core/GangaRepository/Registry.py
python/GangaLHCb/Lib/Tasks/LHCbTransform.py
python/GangaLHCb/Lib/Tasks/LHCbUnit.py

- Fix two typos in Registry.py
- Fix import and when a warning is printed in LHCbTransform code
- Adjust handling of mc_num_units so the parent transform's GaussSplitter can be used to change the first event number.

Typo fixes in Registry code, 6.1.X compatibility fixes to LHCbTasks code

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Schema/Schema.py

These two changes fix bugs that I have come across in the course of working on the thread-safe `GangaObject`. They're both real bugs in the code which were just introduced by accident at some point.
The schema change is for those cases where you have a `GangaObject` which is hidden (and so has no `default_*` config) which has schema `ComponentItem`s items with default values. This fix allows these to work whereas before it would always try to look in the config system.
The second is a small bug which completely breaks `Node.__deepcopy__`. The reason this has not shown before is that no-one actually calls this function as `GangaObject` overrides it and doesn't call the base class. Really this whole method should be killed but while there's a test for it I thought it worth fixing. …

Fix node tests

---

python/Ganga/new_tests/TestSafeSave.py

This is few minor fixes to @drmarkwslater's `TestSafeSave` test to make sure that the things being passed around are valid for the `save_save` function. The main change is using a `LocalFile` instead of a `list`.

Fix testsafesave

---

.travis.yml
requirements.txt

This adds support for running the unit tests on Travis CI which can be seen at https://travis-ci.org/ganga-devs/ganga. This gives us a secondary source of testing on a different system (Travis uses Ubuntu) which reduces the chance of faulty assumptions.
It will only run the unit tests (and maybe in future full GPI tests where limited to `Local`/`Executable`) but its better than nothing. There is a chance of using it in future to test running on OS X too.
I've also just added support for code coverage reporting using [Codecov](https://codecov.io). It's only based on the unit tests but it can supplement any other coverage reporting we have.

Add support for Travis CI

---

python/Ganga/Core/GangaThread/WorkerThreads/__init__.py
python/Ganga/Core/InternalServices/ShutdownManager.py
python/Ganga/GPIDev/Lib/Tasks/TaskRegistry.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/new_tests/GPI/GangaUnitTest.py

This PR deals with improving the startup/shutdown of the queues system.
All I've done is take the code from Shutdown/bootstrap and move it into a startup/shutdown method within the Queues section of the code which is more inline with how it should be handled.
There is still a check for only 1 running queues system but this should be correctly destroyed on shutdown now.
This means I can remove some custom code from the Shutdown method and cleanup the startup of the queues in the bootstrap as this appears to make use of the existing functionality already available.
As this was primarily to make the shutdown more sane I've also removed some lines from GangaUnitTest which are no-longer needed due to improvements in the shutdown of Ganga.

Bugfix/cleanup queues launch/shutdown

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/new_tests/TestGangaObject.py

This adds thread-safe locks to all `GangaObject`s for all schema attributes as well as getting and setting the parent. In addition to this you can, at any time, claim a lock on an object with a `with obj.lock:` context manager and have only the current thread be able to access it.
As well as locking the object itself, it will also claim the locks on all its parents and grandparents (etc.) for safety. This PR makes no distinction between read locks and write locks but I'm not convinced there's a need to distinguish.
This doesn't make any changes to the registry etc. yet but it would be very easy to use the locks here to guarantee thread-safety there too but I haven't yet seen any issues.
This PR obviously competes with some of @rob-c's work in #182 but I feel that this approach is simpler …

Make GangaObject thread-safe

---

python/Ganga/Core/GangaThread/WorkerThreads/ThreadPoolQueueMonitor.py
python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py
python/Ganga/Core/GangaThread/WorkerThreads/__init__.py
python/Ganga/new_tests/GPI/GangaUnitTest.py

In the process of fixing the registry lock-ups I've come across some bugs in the test suite which prevents the tests from running correctly. This primarily affects the queues starting and shutting down correctly but also makes the per-test config system work properly. These are all needed in order to run the `TestQueuedSubmit` test which will be incoming.
This will need to go in before I can merge my registry fixes as it allows the test to run correctly.

Fixes for GangaUnitTest

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/Core/GangaRepository/SessionLock.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py
python/Ganga/Runtime/Repository_runtime.py
python/Ganga/new_tests/GPI/Parallel/TestQueuedSubmit.py

This branch attempts to fix the various deadlocks surrounding the registry. It makes quite a few changes to the registry so it might be easier for some of them to go through commit-by-commit since they are logically grouped there,
Mostly this is making sure that the registry locks are all exception-safe as well as some simplification surrounding the flushing to avoid common deadlocks there. Overall this branch will be flushing to disk less often than before but it should still always be flushing everything on shutdown. I have a WIP for an auto-flushing thread for each registry but that will have to wait for another PR.

Fix registry deadlocks

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Base/Proxy.py

This should address #213.
I would call this a bugfix based upon the example of the discussion I give in the issue above.
As for whether this is included in 6.1.16 of 6.1.17 I leave that for others to decide.

Restoring the use of proxyObject, now much cleaner

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/new_tests/GPI/TestJob.py

Cleans up the `__copy__` methods and uses a `deepcopy` for j.inputdata. Also added a test for job assignment and copy that fails on develop and passes here. Fixes #216.

Make Job copy work correctly

---

release/ReleaseNotes

This is what I could find looking through https://github.com/ganga-devs/ganga/issues?q=milestone%3A6.1.16+is%3Aclosed

Add current release notes for 6.1.16

---

python/Ganga/new_tests/GPI/GangaUnitTest.py

This change enforces that all `GangaUnitTest` tests run in a separate gangadir and that the gangadir is always wiped after the whole test class has finished. Until we have a situation where we want to preserve the gangadir after the test run or run in a specific gangadir, I'd like to keep this code as simple and short as possible.
014e0ea07d9eb356027c9796f551eaf621dd626e is the important change, the other two commits are just minor cleanup.

GangaUnitTest teardown simplification

---

python/Ganga/Runtime/Repository_runtime.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/new_tests/GPI/GangaUnitTest.py

This PR cleans up the GangaUnitTest as well as making it clearer where the repositories are loaded from.
This also moves the removal of the registries to be managed by the registry shutdown which is more sensible.

Moving startup/cleanup of Registries to a sane place

---

python/Ganga/Runtime/Repository_runtime.py
python/Ganga/new_tests/GPI/GangaUnitTest.py
python/Ganga/new_tests/GPI/Loading/TestLazyLoadingSubjobs.py
python/Ganga/new_tests/GPI/Monitoring/TestMonitoring.py

This adds a new test which tests for the lazy loading mechanism on subjobs working in addition to a new test which tests if the monitoring loop has really been disabled and re-enabled by the appropriate GPI commands.

Adding new tests and fixing minor bugs

---

python/Ganga/GPIDev/Lib/Registry/RegistrySlice.py

Fixes #246. The fix is done entirely within the RegistrySlice layer.
Just a side note the RegistrySlice is always created with filters for subjobs so needs care if we ever get rid of that system...
This represents a relatively isolated change so I'm looking to merge tomorrow if possible.

Fix for job.subjobs.select(something...)

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

Adding some more debug code to help with debugging any 'frozen' monitoring threads.

Making warning of dead monitoring more verbose

---

python/Ganga/Core/GangaRepository/Registry.py

As noticed by @rob-c, the dirty status of an object was not being reset after a successful flush. This does this so we should see far few flushes needed.
This may also help with the extraneous flushes on shutdown.

Set the dirty flag to False after a flush

---

python/Ganga/Core/GangaRepository/Registry.py

As @rob-c pointed out, there is a setter function to mark an object as non-dirty.

Use the GangaObject setter to mark as flushed

---

python/Ganga/__init__.py

Disabling heartbeat by increasing default timeout to an obscene number.
I want to keep these as warnings so that we can much more easily debug what's going on but for users who think they're experiencing lockups can change this to be something more sensible like 300.

Disabling HeartBeat checking in Monitoring system by default

---

python/Ganga/GPIDev/Base/Objects.py

Rather than having a lock on every single GangaObject which then propagates up the parent chain, instead just acquire the lock in the object's root object. This is sensitive to altering the parent of an object so extra logic is need in _setParent to lock both the old and new root.
This is a requirement for getting #267 working properly.

Make GangaObjects only lock their root object

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/GPIDev/Lib/Registry/JobRegistry.py
python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py
python/Ganga/__init__.py

This adds an auto-flushing background thread to all registries which flushes all dirty objects with a 30 second gap in between.

Add auto-flusher to registries

---

python/GangaLHCb/Lib/Applications/PythonOptionsParser.py

Adding workaround for dictionary bug

---

python/Ganga/GPIDev/Lib/Job/Job.py

As discussed in the meeting, this will explicitly call flush at the beginning and end of submission. The performance impact of this remains to be seen but it is probably worth it.

Add explicit flush calls at strategic points throughout Job submit

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/Core/GangaRepository/SubJobXMLList.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/new_tests/Unit/TestGangaObject.py

This PR makes the Descriptor  ```__set__``` and registry access exclusively lock to the same thread and have the ```__get__``` and ```__set__``` of the Root of an object exclusively lock on a thread without requiring that the Registry and Descriptor ```__get__``` methods exclusively lock access.
This appears to alleviate the problems experienced when submitting man LHCbDirac subjobs that causes Ganga to lockup after a few minutes of use.
I'm keen to see how this performs on the Jenkins system but this alleviates problems on lxplus for LHCb.
I can't motivate a strong reason why the Registry and Descriptor ```__get__``` methods should mutually lock the root of an object.
If there are strong objections then another solution to #293 is going to have to be found ahead of 6.1.17

Making Registry and __set__ excluively lock and __set__ and __get__ lock but not registry and __get__

---

python/Ganga/Core/GangaRepository/SessionLock.py

I've been working on my new laptop today and when running the test suite I was finding that it was failing towards the end with a `Too many open files` error. Looking into the number of open file handles Ganga had, I was finding that it was increasing steadily with time. Looking in `/proc/<PID>/fd/` I saw lots and lots of `/home/matt/gangadir_testing/TestJob/repository/testframework/LocalXML/6.0/sessions/global_lock (deleted)`.
This PR makes sure firstly that all the calls to `close()` are either guarded by a context manager or by a `finally`. Secondly, it actually closes the `global_lock` file when the session closes down.

Close file handles in SessionLock

---

python/Ganga/Runtime/bootstrap.py

This PR stops Ganga trying to read the GangaRoot dir as a config file.
Given that ATLAS/LHCb people don't seem to see this error anyway, their self.options.config_path is slightly different at this point. I think it's because they have overridden what this removed line is doing. I think therefore that it is safe to remove this but would appreciate someone with ATLAS/LHCb environment testing this.

Don't read GangaRoot dir as a config file

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/feedback_report.py
python/Ganga/Utility/stacktracer.py
requirements.txt

This adds a module to `Ganga.Utility` to provide the dumping of thread stacktraces to a file. It can be used with:
```python
from Ganga.Utility import stacktracer
stacktracer.trace_start('trace.html')
```
That code that can, for example, be added to a user's `~/.ganga.py` or just run live.
It may be useful in the future to incorporate this with `report()` or maybe the monitoring thread heartbeat monitor. I think we should also think about running this alongside the test suite so that locked-up tests can be debugged even on Jenkins.

Add a thread stacktracer

---

python/Ganga/GPIDev/Base/Objects.py
python/Ganga/new_tests/GPI/TestJob.py
python/Ganga/test/GPI/JobCopyConstructor.gpi

This fixes #229 by slightly altering the definition of equality of `GangaObject`s. Previously when doing
```python
a == b
```
they would always be unequal if `b` was 'falsy' (i.e. things like `[]`, `0` and, in our case, an empty `MultiPostProcessor`).
This removes that check completely and (along with some slight tidying to `__eq__`) migrates over another (previously-failing) test.

Fix object equality

---

python/Ganga/new_tests/GPI/GangaUnitTest.py

Re-execing is now not needed for most of Ganga and this was breaking the logging while running tests.
This change allows all logging messages to be correctly captured by the test framework.
@rob-c I believe this addresses the complaint you had last week about logging within tests.

Don't re-exec Ganga when running tests

---

python/Ganga/Core/exceptions.py
python/Ganga/GPIDev/Lib/File/GoogleFile.py
python/Ganga/GPIDev/MonitoringServices/MSGUtil.py
python/Ganga/Utility/logging/__init__.py
python/Ganga/Utility/logging/test.py
python/Ganga/Utility/stomputil/publisher.py

Primarily this is removing the `_get_logging` and `_get_handlers` functions which were used before to get access to the standard library `logging` module. This is replaceable with `absolute_import`.
Additionally it rearranges some imports, deletes unused code and removes unused arguments from some functions.
I realise we are moving towards deprecating this module but in the meantime it's worth reducing the amount of cruft.

Tidy up logging module

---

python/Ganga/Core/InternalServices/ShutdownManager.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/stacktracer.py

Due to an oversight on my part, every single test was waiting up to 5 seconds for the stacktracer to finish its loop before exiting. It's a daemon thread and we're about to delete its file anyway so there's no point in waiting.
This error was causing the integration tests to take 17 minutes on my local machine. With this PR, they now only take 7 and a bit.

Improve stacktracer

---

python/Ganga/Core/InternalServices/ShutdownManager.py

Currently, we are not joining the thread which is maintaining the job monitoring. This results in more than a hundred open threads persisting through the tests which is potentially causing a problem in the Jenkins test system.
Even if it's not causing a problem, it will at least clean up the thread tracer output.

Stop and join job monitoring thread

---

python/Ganga/Core/GangaRepository/Registry.py

Make sure the ```_inprogressDict``` keeps a consistent set of ```id()``` to allow for ```_getReadAccess``` ```_getWriteAccess``` calls at the repo level from causing problems. Possibly alleviates #374.
This was quicker to fix/demonstrate with the PR, if anyone has any further questions please ask.

Make sure consistent id used to defer _getRead and _getWrite

---

python/Ganga/GPIDev/Lib/Registry/RegistrySlice.py

Small cleanup of the use of keys within ```RegistrySlice``` This was 'fixed' as part of making sure ```SubjobXMLList``` worked with subjobs  properly from a user perspective but I've realised it should be used everywhere in the class as it's more correct.
I've checked ```SubjobXMLList``` and it now correctly supports the keys method in a way which doesn't cause problems.
I've tried to make sure that the ```keys()``` method isn't called in lists etc as this is a locked list which if it's called many times behind the scenes due to some poor code there will at least be a performance cost due to the number of calls to the function with the constant (un)locking.

Changing RegistrySlice to have ids better determined

---

python/Ganga/Utility/logging/__init__.py

The `MemoryHandler` is an old style `classobj` not a `type` and so the `super` call breaks in python 2.6. This PR fixes that.

Fix 2.6 compatibility in logging module

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/Runtime/bootstrap.py

Make sure that when an exception is reraised or wrapped in another exception type that the traceback points back to the original errors.
Currently in the test suite, if a test fails during a test submit then the traceback captured by pytest points at line 1659 of Job.py and the traceback looks like:
```python
self = <GPI.Bugs.TestSavannah8534.TestSavannah8534 testMethod=test_Savannah8534>
def test_Savannah8534(self):
from Ganga.GPI import Job, TestApplication, TestSubmitter
app = TestApplication()
j = Job(backend=TestSubmitter(time=30), application=app)
>       j.submit()
python/Ganga/new_tests/GPI/Bugs/TestSavannah8534.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Correctly propagate exception tracebacks

---

python/Ganga/new_tests/GPI/GangaUnitTest.py

Any objections to merging this?
It changes the point at which the import path is changed to be the ```import GangaUnitTest``` or equivalent. This gets rid of a few collection errors for me when I run it on a test system.

Changing when the import path is manipulated

---

python/Ganga/GPIDev/Adapters/IPostProcessor.py

This allows the following to work:
```
tm = TextMerger(files=['stdout'],compress = True)
rm = RootMerger(files=['thesis_data.root'],args = '-f6')
fc = FileChecker(files = ['stdout'],searchString = ['Segmentation'])
cc = CustomChecker(module = '~/mychecker.py')
n = Notifier(address = 'myadress.cern.ch')
j.postprocessors = [tm,rm,fc,cc,n]
```
Fixes #385

Allow assignment of lists to PostProcessors

---

python/Ganga/Runtime/bootstrap.py

Should do a minor part of #379 as it removes the only (bad) reference to the ```global_ns``` which was left in due to the transition from IPython 0.6 to 1.x

Dropping use of global_ns

---

python/Ganga/GPIDev/Base/Objects.py

Put the simpler term first so that if `force_cache` is `True`, it doesn't need to check `fullyLoadedFromDisk()`.
This will hopefully help with some lockups we've been seeing on ganga-ci which are being caused by this section of code.

Reorder terms in conditional

---

python/Ganga/Lib/LCG/ARC.py

Replacing the `getConfig` line that shouldn't have been removed.

Setup the config properly for the ARC backend

---

python/Ganga/__init__.py

I spotted that at some point (very recently) that I accidentally pushed some minor changes the monitoring config which weren't caught as being a bit strange.
This PR restores that we should use 5 threads in the Monitoring logic of what to as per ```update_thread_pool_size``` and that the number of jobs which should be processed in parallel should be at least 50 according to ```numParallelJobs``` I think these got confused and mix up what is going on.
Does anyone think we can/should bump the number of parallel (sub) jobs being processed by a backend to be much larger than 50? This was originally introduced due to the combination of lazy-loading and slow backend communication leading to extremely slow monitoring behaviour and timeouts.
If anyone thinks we should change these config settings …

More default config for jobMon

---

python/Ganga/Runtime/bootstrap.py

When reviewing #395 I didn't realise that the error message that spawned that PR was:
```
DeprecationWarning:  global_ns is deprecated, use module instead.
```
As such, simply removing `global_ns` has broken running scripts with `execfile` inside Ganga. This PR correctly *replaces* `global_ns` with `module` rather than removing it entirely.
What we're exporting to what probably needs a little looking at (i.e. not exporting the namespace of bootstrap.py into `locals()`) but this for now mostly maps to the old behaviour.

Export the GPI into the global namespace of Ganga

---

python/Ganga/GPIDev/Base/Proxy.py
python/Ganga/test/Unit/TestProxy.py

Until now it seems that while schema attributes were being correctly stripped and wrapped as they were passed through the proxy-interface, the same was not being done for arguments and return values of exported methods. 
All proxy-exported methods are accessed via `ProxyMethodDescriptor` which now correctly removes the proxies from all incoming arguments and adds them to any return value.
This depends on #392 to make one of the `GangaList` tests pass so I will rebase this on develop once that is merged.

Add and remove proxies on all proxy method args

---

python/Ganga/GPIDev/Adapters/IPrepareApp.py

This cleans up some code in the IPrepareApp and gives a hook to allow derrived classes to quickly and easily copy a file into the prepared state folder during the prepare step.
This is useful for my LSST work where I'm already using this and it fixes a typo which was left from this function already existing 4x in the exiting code.

Fixing prepare step bug

---

python/GangaDirac/BOOT.py
python/GangaDirac/Lib/Files/DiracFile.py
python/GangaDirac/__init__.py

If it is in the `__init__.py` then some information set by the user will
not yet be available. Deferring it to point of use allows user settings
to be used.

Move construction of DiracLFNBase into a function

---

python/GangaDirac/old_test/GPI/Files/TestDiracFile.py
python/GangaLHCb/old_test/Bugs/JIRA1943.gpi
python/GangaLHCb/old_test/Bugs/Savannah13943.gpi
python/GangaLHCb/old_test/Bugs/Savannah20538.gpi
python/GangaLHCb/old_test/Bugs/Savannah36400.gpi
python/GangaLHCb/old_test/GPI/DaVinci/TestDaVinci.py
python/GangaLHCb/old_test/GPI/Dirac/GaudiPythonDirac.gpi
python/GangaLHCb/old_test/GPI/Dirac/RootTestSubmitDirac.gpi
python/GangaLHCb/old_test/GPI/Dirac/TestSubmitDirac.gpi
python/GangaLHCb/old_test/GPI/GaudiPython/TestBender.gpip
python/GangaLHCb/old_test/GPI/GaudiPython/TestGaudiPython.py
python/GangaLHCb/old_test/GPI/GaudiSplitters/SplitByFiles.gpi
python/GangaLHCb/old_test/GPI/GaudiSplitters/TestDiracSplitter.py
python/GangaLHCb/old_test/GPI/GaudiSplitters/TestSplitBigDataset.gpi
python/GangaLHCb/old_test/Lib/DIRAC/TestLHCbGaudiDiracRunTimeHandler.py
python/GangaLHCb/old_test/config/default.ini
python/GangaLHCb/old_test/config/localxml.ini
python/GangaLHCb/old_test/config/remote.ini
release/tools/schema_gen.sh
release/tools/schema_test.sh

The main important change in this PR is that to  `python/GangaLHCb/old_test/config/localxml.ini`. We now need to explicitly add `GangaDirac` to the runtime path before `GangaLHCb` so that the config has been set up by the time that the LHCb statup runs.
The other changes are just fixes to accidental leftovers from the `test`→`old_test` changes.

Fix LHCb test imports

---

python/Ganga/GPIDev/Schema/Schema.py

When getting the default value of a schema item, rather than relying on the GPI being populated and then having to strip the proxy from the result, instead search in the plugin system for the requested class object.

Simplify default object lookup

---

python/Ganga/Utility/Shell.py
python/Ganga/Utility/execute.py
python/GangaDirac/Lib/Utilities/DiracUtilities.py

When working to port some of the DIRAC tests I came across a feature of `Ganga.Utility.execute.execute()` which allows it to update a dictionary based on the environment of the called command. This was accidentally broken in [`c637500`](https://github.com/ganga-devs/ganga/commit/c637500b68ebf9bc5e45ccbf03559868152d1949#diff-09802c04483863469997ddb0cb23bea3) but since the Dirac test was the only thing using it, it went unnoticed.
This PR fixes that command and then changes the two existing uses of `get_env_from_arg()` to use `update_env` instead.
Historically, it seems that `update_env` was added to the queues system's version of `execute()` in b46aa4ec327a494135e3092a2f02ec968949dd41 by @alexanderrichards before being migrated to the standard `execute()` function some time later.

Fix execute's update_env

---

bin/ganga
python/Ganga/PACKAGE.py
python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/Runtime.py
python/Ganga/Utility/Setup.py
python/Ganga/__init__.py
python/Ganga/testlib/GangaUnitTest.py
python/GangaAtlas/PACKAGE.py
python/GangaAtlas/__init__.py
python/GangaCMS/__init__.py
python/GangaDirac/__init__.py
python/GangaGaudi/__init__.py
python/GangaLHCb/__init__.py
python/GangaNA62/__init__.py
python/GangaND280/PACKAGE.py
python/GangaPanda/PACKAGE.py
python/GangaPanda/__init__.py
python/GangaSAGA/__init__.py
python/GangaSNOplus/PACKAGE.py
python/GangaSuperB/__init__.py
python/GangaTest/__init__.py

This removes the re-exec machinery completely and makes Atlas work sensibly without it. Other than just the stopping of re-exec, this also checks for a `standardSetup` function in the `__init__.py` of any runtime packages and calls this during `initEnvironment`. This is essentially a name swap from `getEnvironment` as this is often used as a more general hook anyway. 
We could possibly split the runtime setup calls out completely from `initEnvionment` to make it obvious what's happening but I'll leave that for someone else to decide 😄 
Fixes #404, #52

Remove Reexec machinery

---

python/GangaPanda/Lib/Athena/AthenaPandaRTHandler.py

Minor addition from the previous set of Atlas fixes which I missed (#470).

Added missing homepackage setting when atlas_release is not set

---

python/Ganga/Lib/LCG/ARC.py

There was some old proxy delegation code from the initial copy+paste job from CREAM backend that stopped the resubmission mechanism. This removes this and fixes #50

Removed proxy_delegation which was C+P error from CREAM

---

python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py

There is currently no protection against two threads increasing or decreasing the same ShareRef at the same time. I believe this has been causing a few of the lockups that I have seen in testing PRs and locally.

Synchronise increase and decrease of ShareRefs

---

python/Ganga/testlib/fixtures.py

This is a small update to a previous change by @rob-c to make sure that the pytest-run tests' gangadir matches that of the other tests.

Put pytest tests' gangadir in the same place as other tests

---

python/GangaDirac/Lib/Files/DiracFile.py
python/GangaDirac/Lib/Files/__init__.py
python/GangaDirac/Lib/Server/DiracCommands.py
python/GangaDirac/Lib/Splitters/SplitterUtils.py
python/GangaDirac/Lib/Utilities/DiracUtilities.py
python/GangaLHCb/Lib/RTHandlers/LHCbRootDiracRunTimeHandler.py
python/GangaLSST/Lib/Im3ShapeApp/Im3ShapeApp.py

These are some change I've made in order to get the legacy DIRAC tests ported over (PR incoming soon). The changes to the imports are needed in order to correctly mock the `execute` function. 
The removal of the call to `getReplicas()` was done since the mock system was flagging that `execute` was being called multiple times for a single call to `replicate()`. It seems like the calls were added in order to be able to call `replicate()` even if `locations` was not set (by requesting the current replica SEs from DIRAC). The change was made in ecbb34b71bf14247205d9a8f81844e73939bd979 but the commit message doesn't help with working out the exact reason. In fact it doesn't matter too much since it's possible to call DIRAC's [`replicateFile()`](http://diracgrid.org/files/docs/CodeDocumentation/ …

Small DIRAC tidy

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/Config/Config.py
python/Ganga/Utility/Config/__init__.py
python/Ganga/Utility/Config/tests.py
python/ganga/__init__.py

This makes no functional change to the bootstrap code, it simply refactors a part of the `configure()` method. It adds a new static method called `get_config_files` which gives the list of all the config files, ready to be passed to `Ganga.Utility.Config.configure()`. This allows us to load the config files in a consistent way, even when we are only running unit tests without having performed the full bootstrap procedure.

Factor out the config file finding in bootstrap

---

python/GangaDirac/Lib/Files/DiracFile.py

As an addendum to #509, this makes sure that the replicated SE is not added to `locations` if it's already there.

Don't add the new SE to locations if it's already present

---

python/Ganga/GPIDev/Lib/File/scripts/MassStorageFileWNScript.py

I think in the transition from inline script to separate file, the escaped newline character was not changed and so this added extra string noise to the `__postprocesslocations__` file. This PR removes that.
Fixes #519.

Remove spurious '\' from newline character

---

python/Ganga/Runtime/bootstrap.py

Fixes #546 
This PR is very short but worth documenting. I'm changing the IPython hook to be the `pre_run_code_hook` which is run after the text input in a command line has been finished.
This replaces our use of the `pre_prompt_hook` which is executed every time a user hits enter which for complex functions can be quite a few times before they've finished inputting a command.
The result is that the logging no longer flushes and interrupts the user input.

Fixing the IPython logging hook to not flush during text entry

---

python/GangaService/Lib/Server/server-script.py

The GangaService was using stderr to check for the output of commands sent. Due to the change to Ganga using the stdout properly (instead of stderr) this stopped the Service reporting any output. This small PR fixes this.

Switch GangaService from reading stderr to stdout

---

python/GangaDirac/Lib/Utilities/DiracUtilities.py

This ensures that the LHCb plugin has finished loading before the proxy is created. Objects should not be created at import time.
This is one half (the less controversial half) of #555.

Defer creating the proxy object until the first time it is requested

---

python/Ganga/Runtime/bootstrap.py
python/GangaDirac/Lib/Utilities/DiracUtilities.py

This causes every call to DIRAC's `execute()` function to ask to make a proxy if it has expired. Currently, if there is no proxy present when Ganga starts, no proxy will ever be created and errors like:
```
AttributeError: 'NoneType' object has no attribute 'get'
```
will be raised.
Perhaps this is unsafe because it might be called in a background thread but somehow we need to get a proxy created.

Create DIRAC proxy

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py

The code in `OfflineGangaDiracSplitter` is checking for already used lfns with:
```
if iterating_LFN in chosen_lfns:
```
This is fine until the `chosen_lfns` list goes above a few hundred at which point everything grinds to a halt. This PR changes `chosen_lfns` to use a `set` instead. In a very quick & dirty splitting test over the 2015 data, this speeds this part of the function (not the whole thing) up from 2+ hours (on a ~fast desktop) to ~1 sec.
There are still other areas in this code that could be looked at to speed things up but this is a big improvement with minimal changes.

Making chosen_lfns use sets instead of lists

---

python/GangaLHCb/__init__.py

For consistency (and to prevent it being reset between test runs), set the LHCb env cache as the default value rather than the session value.
I think this should fix the nightly tests.

Set the default value rather than the session value for the LHCb cache

---

python/GangaDirac/Lib/Files/DiracFile.py

Fixing a small typo introduced in 6360234a159c84f8d8716d34c4004799cccf6157.

Fixing typo

---

python/Ganga/GPIDev/Credentials/AfsToken.py
python/Ganga/GPIDev/Credentials/GridProxy.py
python/Ganga/GPIDev/Credentials/__init__.py
python/Ganga/Lib/LCG/ARC.py
python/Ganga/Lib/LCG/CREAM.py
python/Ganga/Lib/LCG/Grid.py
python/Ganga/Lib/LCG/GridSandboxCache.py
python/Ganga/Lib/LCG/GridSimulator/GridSimulator.py
python/Ganga/Lib/LCG/GridftpSandboxCache.py
python/Ganga/Lib/LCG/LCG.py
python/Ganga/Lib/LCG/LCGOutputDownloader.py
python/Ganga/Lib/LCG/LCGSandboxCache.py
python/Ganga/Utility/GridShell.py
python/Ganga/__init__.py
python/Ganga/old_test/Bugs/Savannah32201.gpi
python/Ganga/old_test/GPI/LCG.gpi
python/GangaAtlas/Lib/ATLASDataset/ATLASDataset.py
python/GangaAtlas/Lib/ATLASDataset/DQ2Dataset.py
python/GangaAtlas/Lib/AthenaMC/AthenaMCDatasets.py
python/GangaAtlas/old_test/GPI/TestAtlas.ini
python/GangaAtlas/scripts/athena
python/GangaAtlas/scripts/athenamc
python/GangaLHCb/LHCb.ini
templates/CONFIG_TEMPLATE.INI
templates/CONFIG_TEMPLATE_Atlas.INI
templates/CONFIG_TEMPLATE_LHCb.INI

This is a clean-up of the code in `Grid.py` to change it from being a stateful class being passed around into a module of free functions which work independently of each other. Historically, the main reason for this being a stateful class was they a user might want to have a `Grid` object for 'EDG'  and one for 'GLITE'. This is now not needed as EDG is no more (since lots of years).
Of course this necessitates a number of changes across the board but overall it is removing code.
The reason I am making these changes now is that in my [credentials branch](https://github.com/ganga-devs/ganga/compare/feature/credentials) I ended having to make a number of these changes in order to have proxy prompts happen at the right times. My idea here is to start breaking out some of the larger changes in …

Simplify Grid

---

python/GangaLHCb/Lib/GaudiRunApp/GaudiRunAppHandlers.py

This PR just adds a warning to the submission of jobs using the GaudiRun app as it's to be regarded as in-development.
I'll merge once the tests have passed unless there are any objections.

Adding a warning to the job submission

---

python/Ganga/GPIDev/Lib/Job/Job.py

Just a quick PR for a 1 line fix. I'll merge after the tests have passed.
This fixes a bug where in a lot of cases the job status wasn't being loaded correctly from the lazy loading index. This is a quick 1 line fix to make sure that it is indeed loaded from the index and not from the actual underlying object which hasn't been loaded.

Fixing bug to stop status always being evalled

---

python/Ganga/Utility/logging/__init__.py

This is a bug which only really effects the tests, however it does mean that there are some few 100 Handles left associated with the logging system when running all of the tests back to back.
I'll merge this once the tests complete

Fixing logger on shutdown in tests

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py
python/GangaLHCb/Lib/Applications/PythonOptionsParser.py
python/GangaLHCb/Lib/GaudiRunApp/GaudiRunApp.py
python/GangaLHCb/Lib/GaudiRunApp/GaudiRunAppUtils.py
python/GangaLHCb/Lib/GaudiRunApp/PythonOptsCmakeParser.py

This PR adds the readInputData functionality into the GaudiRun app...
I was a little surprised at first but this appears to be a very quick thing to do so I think I see some appeal in addition to the LHCb users getting their datasets from bookkeeping this way.
I based this heavily on the equivalent code in the old-style LHCb apps but added some changes to make this more 'cmake'-like. This still uses gaudirun to pickle a file and such as before.
Once the test here passes I'll merge this PR and do some additional testing before looking into making a beta release to LHCb.
(I think I've spotted a bug in LHCbDataset I'd like to make 100% sure doesn't go out into testing as it would be quite annoying)

GaudiRun adding read input data

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py

This PR just stops the rmrf method from renaming a file which is to be deleted too many times.
Files here are moved and then deleted due to some problems with AFS lockfiles so that any folders which can't be deleted due to a stray lock file won't get in the way in the XML repo in the future.

Stopping filenames getting excessively long

---

python/Ganga/Utility/Config/Config.py
python/GangaLHCb/test/GPI/TestSubmitLocal.py

Making LHCb test external as it's vulnerable to `SetupProject DaVinci` failing. We cannot demand this tests pass in this case.

Make test external

---

doc/UserGuide/InstallAndBasicUsage.rst

removing the -v lines on lhcb-prepare
Waiting on the test to  finish which gets in the way of editing docs on the fly
Should we consider putting the docs in a second repo so that people can contribute to them in a much more informal way because collecting things for a PR and then re-testing Ganga is a bit overkill for submitting changes at the level of typos to the docs. This is the advantages of wiki's etc...

removing bad option on lhcb-prepare (docs)

---

python/Ganga/Core/GangaRepository/GangaRepository.py
python/Ganga/Core/GangaRepository/GangaRepositorySQLite.py
python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/Core/GangaRepository/SubJobXMLList.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/GPIDev/Lib/Registry/JobRegistry.py
python/Ganga/test/GPI/Internals/TestRepo.py
python/Ganga/test/GPI/Loading/TestLazyLoading.py
python/Ganga/test/GPI/Loading/TestLazyLoadingManyJobs.py
python/Ganga/test/GPI/Loading/TestLazyLoadingSubjobs.py
python/Ganga/test/GPI/newXMLTest/TestNestedXMLWorking.py

This is an extension of #584 which moves to make use of the `GangaObject._inMemory` boolean for tracking an objects loaded state (introduced in the former #PR)
This touches quite a few files so once I'm certain this works I can look at merging this into #584 ahead of merging that into develop.

Moving to use ._inMemory everywhere for tracking object loaded state

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/GPIDev/Lib/Job/Job.py
python/Ganga/test/GPI/FileTests/TestSJIDName.py
python/Ganga/test/GPI/TestSJSubmit.py

Fixed #617 
I've fixed #617 by more carefully defining the SJID test and I've added an additional bit of logic to Job.py to avoid stalling (or worse!) due to very bad behaviour.
I've also added a few new short tests to test the resubmit code around subjobs as this wasn't being tested in an independent way where picking up this bug might have been slightly quicker/easier.

Fixing bug where test deadlocks and other nasties

---

python/GangaLHCb/Lib/GaudiRunApp/GaudiRunApp.py
python/GangaLHCb/Lib/GaudiRunApp/GaudiRunAppHandlers.py

This is a PR with some updates for GaudiRun.
I've changed the WN code to stream the stdout/stderr from the command directly as I've hit a few occasions where the stream has been lost from record.
(Plus the code feels more professional than an os.system call, although we may want to check return-codes)
I've tested and can switch between gcc48 and gcc49 with no issues on the Localhost and still execute jobs on the grid.
I'd like to get this into 6.1.21 if we've not tagged this for release yet as it puts the GaudiRun in a nice place where I only need to work on Gauss support and some general support for more complex workflows such as with unique data files per subjob as well as MassStorageFile support.
Fixes #621
Fixes #622
Fixes #624
Fixes #626

Additional Cmake support

---

python/Ganga/Lib/LCG/LCG.py
python/Ganga/__init__.py

As we have discussed in the past, we want to be able to disable the LCG system by default without affecting anyone who is currently using it. This PR achieves this by changing the default `[LCG]VirtualOrganisation` to `''` and adding a check to only enable the LCG system if the VO has been set to *something*.
In any case, a default VO of `dteam` made little sense anyway.
I've labelled this for 6.1.22 but it could be brought forward to 6.1.21 if people wanted.

Nicely disable LCG

---

release/ReleaseNotes-6.1.21

Adding some release note information, not complete but enough info for LHCb/Core/Core+Dirac users.
I'm not sure what has changed in any of the other plugins but I think this is what has changed in Core/Dirac/LHCb since the last release.

Adding some 6.1.21 release notes

---

python/Ganga/Utility/GridShell.py
python/GangaDirac/Lib/Server/DiracCommands.py

I'm keen to get this in (last minute I know) for 6.1.21 as this is a quick fix for splitting of jobs which has been highlighted to us as being problematic (at least for LHCbDirac users).
I'll run some submit tests now and see what I get to check this.

Fix for LHCb offline Dirac splitter

---

python/Ganga/Utility/GridShell.py

After or if the `GLITE_ENABLED` is set to false in the config there is no need to warn the user about missing files which will/should never be used.
Goes from:
```
INFO     LCG config is not set. Please set [LCG]VirtualOrganisation to your VO (e.g. "gridpp") or disable LCG with [LCG]GLITE_ENABLE=False
WARNING  Configuration of GLITE for LCG:
WARNING  File not found: /afs/cern.ch/sw/ganga/install/config/grid_env_auto.sh
```
```
INFO     LCG config is not set. Please set [LCG]VirtualOrganisation to your VO (e.g. "gridpp") or disable LCG with [LCG]GLITE_ENABLE=False
```
As long as we're not creating a proxy on systems when they start by default just because the tools are there I'm happy to wait until 6.1.22 for this to go in.

Getting rid of bad warning when it's simply not needed

---

python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

This bug was highlighted by looking through the old_tests that were run against 6.1.21.
At what point in the release process are these tests run? Was there an email saying where the test results are located? I think I may have missed that email as I can't find one in my inbox.
As it stands this looks like a bug against LHCb Tasks so I'll try and see if I can run some simple task examples for LHCb and if not I'll push out the release with a caveat for tasks users. (I'm hoping to avoid this)

Fixing bug in old_tests

---

python/Ganga/Runtime/bootstrap.py

Fixing a bug in how the GangaTest adds itself to the RUNTIME_PATH. This fixes it so that it works for my LHCb environment which has additional plugins for testing.

Fixing GangaTest Runtime env modification

---

python/GangaAtlas/PACKAGE.py

In the recent changes to the plugin setup and removal of REEXEC I missed a change to the rucio client import that was needed for (very) old Athena releases. This fixes that.

Change PYTHONPATH to syspath for rucio import

---

python/Ganga/Lib/LCG/Grid.py

Submission using ARC backend fails due to an incorrect submission interface being used in the arcsub command.

Fix incorrect arcsub command

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py

The message says that property ignoreMissing = False but the property
of FileSplitter is called ignoremissing. I adjusted the error message.

Fix error message in FileSplitter

---

python/Ganga/GPIDev/Base/Proxy.py

This PR resolves https://github.com/ganga-devs/ganga/issues/692. Essentially checking for base type `basestring` rather than `str` such that unicode objects are also caught. It also includes some code clean up as mentioned in the above issue.

Unicode proxystrip

---

python/GangaDirac/Lib/Backends/DiracBase.py
python/GangaDirac/Lib/Files/DiracFile.py
python/GangaDirac/Lib/Files/WNInjectTemplate.py
python/GangaDirac/Lib/Files/downloadScript.py
python/GangaDirac/Lib/Files/uploadScript.py
python/GangaDirac/__init__.py

These are some changes broken out from #691
I've confirmed the changes in `GangaDirac/__init__.py` Fix #685 
I've also made several small changes to the DiracFile and it's scripts which are inserted into jobs. This fixes the DiracFile so that it works correctly as an outputfile for Local jobs.
In addition I've fixed some minor bugs where the DiracFile wasn't uploaded to the correct LFN.
I think this needs to be merged given the DiracFile is currently broken (I suspect a lot of changes due to the `__construct__` changes).

Fixes for DIRACserver job kill problem and DiracFile used as Batch/Local outputfile

---

python/Ganga/test/GPI/TestSJSubmit.py

This test randomly failed on Jenkins due to having to kill a job to mark it as failed. This is bad so I'm adding some minor changes which should fix it.

Force status transition in TestSJSubmit to prevent race condition failures

---

python/GangaLHCb/Lib/Applications/GaudiExec.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

I've refactored some of the code to fix a few minor bugs in how the jobs work when a new job is copied.
Now every new job regenerates all of the script files from scratch. However the prepared state of the application remains the same.
I have tried copying a Local job, modifying it's backend to Dirac and resubmitting it and everything now works as expected.
This also makes the code in the master_prepare methods a bit easier to read.
I've also cleaned up the schema slightly so that all of the generated scripts are stored in 1 LFN and all of the scripts for the application prepared state are stored in another.
Now when unpreparing an application the reference to the LFN is set to None and there is no way to automatically remove these files which may be on external storage (this is …

Fix GaudiExec prep

---

python/Ganga/GPIDev/Base/Objects.py
python/GangaLHCb/Lib/Applications/GaudiExec.py
python/GangaLHCb/Lib/Applications/GaudiExecUtils.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py
python/GangaLHCb/test/GPI/TestGaudiExec.py

This PR migrates the GaudiExec to use a list in the `options` attribute and makes the necessary modifications to the script.
I think asking the users to add an extra `[ ]` around their arguments isn't too bad and unfortunately I can't get this to work unless I mark the schema attribute as being a list.
Do we support anywhere the mixing of list and none list assignment to attributes in the Schema I couldn't find an example of this that fully worked?
In addition to this I've fixed:
1. Bug where the sys.argv[0] shouldn't be passed to the running script on the WN.
2. Bug where scripts for subjobs > 0 were being lost to the ether during submit.
3. Bug due to bad support of DiracFile for opts files
4. Bug in GangaObject where objects would be unloadable from disk due to defaults conflicting …

Multiple options for GaudiExec

---

.travis.yml
python/Ganga/test/GPI/LCG/TestLCG.py
python/Ganga/test/Unit/LCG/TestGrid.py
requirements.txt

This adds a number of tests for the LCG and Grid systems using the mock module to avoid communicating with any external systems. 
This builds on #619.

Add mocked tests for LCG and Grid submission

---

python/GangaLHCb/Lib/Splitters/GaussSplitter.py

Fixes #631 
After running some quick tests this should be all that is required for GaussSplitter to be correctly supported by the `GaudiExec` application.
I've added the appropriate splitter options into the `extraOpts` attribute for each subjob and have verified that each subjob is correctly unique and that the job scripts appear to be picking up the correct extraOpts script which is created and sent to the WN.
I've managed to get as far as getting back a file, but I'm not an MC expert I was cobbling together a solution from an old tutorial so this may be rough around the edges.
If the 6.1.23 release hasn't been finalised I'd like to merge this as it should be working.

Enabling GaussSplitter support for GaudiExec

---

python/GangaPanda/Lib/Jedi/Jedi.py
python/GangaPanda/Lib/Panda/Panda.py

As we now auto flush and the `GangaList` stuff is all fixed, `_commit` should be removed.

Remove _commit references from Atlas code

---

python/GangaDirac/Lib/RTHandlers/ExeDiracRTHandler.py

As described in issue [#521](https://github.com/ganga-devs/ganga/issues/521) the args of Executable apps were getting lost on the Dirac backend. This is fixed simply by switching shell=True to shell=False in the call to subprocess.call.

Fixing Executable on Dirac backend.

---

python/GangaLHCb/Lib/Splitters/GaussSplitter.py

Removing LHCbApp references in GaussSplitter
Having this in the splitter causes problems. I'm removing it from 6.1.25 onwards as any bugs from not having this I would argue are user/application bugs.

Removing LHCbApp references in GaussSplitter

---

python/Ganga/Lib/Condor/Condor.py
python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/athena-local.sh
python/GangaAtlas/scripts/athena

This PR addresses a few things:
* I've had Atlas report an issue in some Condor installs that the stdout file is slow to be populated which leads to odd errors. This may or may not be directly related to Atlas but I've put in a fix to wait up to 10mins after first seeing the job has finished for the stdout to be filled. Fixes #741 
* GangaAtlas was being very particular about how the job options were specified. This was basically due to legacy code where the JOs were originally only thought to be a file that you'd ship. This is now far too restrictive so I've added a `command_line` option to Athena that is passed straight through to the final Athena call. This means it runs exactly as you would from the command line without translation. Fixes #542 
* Combined with the above was an issue …

Fix Condor errors and some Atlas cmd line problems

---

python/GangaPanda/Lib/Athena/AthenaJediRTHandler.py

Jedi needs the `--trf` flag set for TRF jobs. This makes sure this is set correctly.

Make sure the --trf option is added to Jedi jobs

---

python/Ganga/Utility/util.py

Fixes #758 moves to use a different method to get the fqdn of the site we're running on. Used to identify the host machine in various sections of the code.
I've had a look at the docs and I'm not sure if we need to protect against any other form of exception. But if this is called and cached I don't see too much risk in having the code just check for a socket.error

Switching to getFQDN

---

python/Ganga/test/GPI/LCG/TestCREAM.py
python/Ganga/test/GPI/LCG/TestLCG.py

This step adds a small step to load the config and to not run the LCG tests when they're known to fail.
This adds <1 sec to the discovery of the tests so I'm planning to merge this once everything works to run some nightly tests. I'll revert if this causes problems.

Adding skip test around LCG tests

---

python/Ganga/test/GPI/LCG/TestCREAM.py
python/Ganga/test/GPI/LCG/TestLCG.py

Reverts ganga-devs/ganga#777
Hitting the 1 button revert option as was discussed in the previous PR.
This is unfortunately mute as the DIRAC tests are now all stalling preventing this code from being properly tested.

Revert "Adding skip test around LCG tests"

---

python/Ganga/Core/GangaRepository/SessionLock.py
python/Ganga/Runtime/Repository_runtime.py
python/Ganga/testlib/GangaUnitTest.py
python/Ganga/testlib/fixtures.py

Just a quick PR to highlight the effect of adding whitespace to the test directory name.
This shouldn't effect tests run through the `PR Builder` but will highlight problems in the `nightly` builds.
Depending on how people feel I propose changing `gangadir_testing` to `gangadir testing` in the test-suite to catch problems with whitespaces which crop up atm under some tests but not others.
I'm happy to revert if there is opposition, but I thought this might be a good idea.

Adding whitespace to all test dirs

---

python/Ganga/testlib/GangaUnitTest.py

Fixes #799 
I've changed the default config file to point to a non-existent path so that changes to `~/.gangarc` on dev machines (and Jenkins) are isolated from the running of the tests.
This should hopefully reduce confusion and will mean anyone running a test doesn't run the risk of torching a production repo while they do so.
This appears to work without problem and I've verified it solved my problem with my tests taking forever to shutdown while they torched my 2k Job test repo.
Can someone review this as I'd like to merge this for other dev work I'm doing. Thanks!

Making sure ~/.gangarc file isn't parsed during startup of tests

---

python/Ganga/Core/MonitoringComponent/Local_GangaMC_Service.py

This adds a `return True` for the case that a credential is valid and an exception isn't raised.
If this is not here AFS users get an error that the AFS token is invalid and that the monitoring will stop for it.
@milliams Does this look sensible compared to the design of the new credentials?

Adding return True for a credential which didn't throw an exception

---

python/Ganga/GPIDev/Lib/Job/Job.py

Changing the Job.py outputfiles unique test to just use an append, extending a list from a set from the original list breaks the order ad the set function sorts the input.
This doesn't effect too many tests but does interfere with the File tests when running on different machines.
I'll merge this once the tests pass as this fixes a minor bug which has already been reviewed in a better way on top of the 6.3 branch.

Fixing unique test for outputfiles

---

python/Ganga/Runtime/Repository_runtime.py

At present the `checkDiskQuota()` function is printing errors like:
```
df: `\'/disk/homedisk/home/mpw/ganga/ganga/python/gangadir testing/TestSJSubmit/repository/testframework/LocalXML\'': No such file or directory
df: no file systems processed
```
`Popen` will do the quoting automatically when passed a list of arguments in non-shell mode and so the presence of the `quote` function is causing spurious double quoting.

Don't quote arguments passed to non-shell Popen

---

python/Ganga/Core/exceptions.py
python/Ganga/GPIDev/Base/Proxy.py
python/Ganga/GPIDev/Credentials/CredentialStore.py
python/Ganga/Runtime/Repository_runtime.py
python/Ganga/Runtime/bootstrap.py

This just stops the user being confronted with a stack trace when a proxy(credential) doesn't exist.

Clean up exceptions

---

python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/GPIDev/Credentials/ICredential.py
python/Ganga/GPIDev/Credentials/__init__.py

This PR adds dummy Voms and Dirac proxy classes to allow us to load jobs from 6.3.x within Ganga 6.2.x. This is needed and prevents data corruption when moving between versions (as I'm sure some users will inevitably try to do)
I'm happy to move the classes around/rename them/completely rewrite them and I can look at if they're exposed to the GPI and try to prevent this. However the classes need to be present within Ganga in some form to prevent data corruption.
The intention was to hide these in a file which is being removed in the transition to 6.3.x so this will not effect us when this is merged.

Bugfix/forward compatibility with 6.3

---

python/Ganga/GPIDev/Schema/Schema.py
python/Ganga/Utility/Config/Config.py
python/Ganga/Utility/Config/__init__.py

This removes a bunch of unused and unnecessary code from Config as a first step towards making it more easily loadable and un-loadable.
The biggest change in here is that `getConfig()` will no longer *create* a config section if it doesn't find one. This is possible since we are now explicit about using `makeConfig()` in our `__init__.py` files.

Cleanup Config.py

---

python/Ganga/Utility/Config/Config.py

This fixes a bug in the config system that running the new user code without a .gangarc would lead to a crash. This fixes it. This is present in the 6.2.1 testing branch.

Fix config on start up

---

python/GangaDirac/Lib/Backends/DiracBase.py

The signature for one of the 10 BackendError calls is missing the first argument ("Dirac"). (one line fix) This causes the following incorrect error message when a job fails:
```
raise BackendError('Problem retrieving outputsandbox: %s' % str(getSandboxResult))
TypeError: __init__() takes exactly 3 arguments (2 given)
```

BUGFIX: Fixing error with backend missing when raising BackendError

---

python/Ganga/Utility/execute.py
python/Ganga/test/GPI/LCG/TestCREAM.py
python/Ganga/test/GPI/LCG/TestLCG.py
python/Ganga/testlib/mark.py

This PR adds a more complex fixture which allows us to skip a test if we know that the config will always cause the test to fail.
I'd like to merge this into `develop` to get the nightly tests working for all backends.
I know this can be viewed as an enhancement but I'm keen to get the nightlies running with core tests for LHCb so I'm viewing this as a bugfix as the LCG tests will incorrectly fail when inside an LHCb environment.
Does anyone have any objections to me merging this?

Adding a more complex fixture to protect LCG tests

---

python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

This fixes some issues in LHCbDataset #855 . The ```difference```, ```symmetricDifference``` and ```union``` functions were calling ```extend()``` with a ```[list(set)]```. So the set was being changed to a list but then put inside another list which was causing problems.
I think this is just a hangover from when the code was changed to use ```extend``` instead of the now-defunct ```construct``` function.

Some fixes to LHCbDataset

---

python/GangaGaudi/Lib/Applications/GaudiBase.py

Fixes #860. Added in the ```force``` argument for the ```unprepare``` function in the GaudiBase. Doesn't actually do anything but other places call ```unprepare``` with a force flag so I added it in.

Fix for prepare in old style apps

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/Config/__init__.py
python/Ganga/Utility/Runtime.py
python/ganga/__init__.py

Fixes #863  This moves more code out of the bootstrap into the correct utility and calls it from both `ganga` and during normal startup.
Rough and ready so feel free to fix/improve/edit/take-inspiration from this PR.

Moving some code around and allowing for 'ganga' to load plugins 

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/Utility/Config/Config.py
python/Ganga/Utility/Config/__init__.py

Fixes #829 . Now the config files and command line options are set as UserValues rather than SessionValues so they take precedence over the later plugin loaded options. The command line options are loaded after the config ones, so they are still top.

Fix for user configurations

---

python/Ganga/Core/GangaRepository/FixedLock.py
python/Ganga/Core/GangaRepository/GangaRepositoryXML.py
python/Ganga/Core/GangaRepository/SessionLock.py
python/Ganga/__init__.py

This was something I was playing with over the weekend mainly.
This PR shows how we can have the simplest lock possible which only prevents Ganga from running multiple sessions. The shutdown is relatively friendly and doesn't have a stack trace.
This would likely be useful for non-POSIX envs where a user would be able to launch similar to:
```
IPYTHONDIR=/tmp/somePath ganga -o'[Configuration]lockingStrategy=Fixed'
```
This may be useful for unusual installs or debugging (or even in testing as this reduces a lot of I/O).
I'm not sure if someone else has an idea of how they would like to solve this but this would be what I suggest.
NB:
filelock in python still relies on posix locking (I think) if it's there so migrating SessionLock to this is only a cleaning up exercise and doesn't help if …

Adding simplest lock to Ganga

---

python/Ganga/GPIDev/Base/Proxy.py
python/Ganga/GPIDev/Schema/Schema.py
python/Ganga/Runtime/GPIexport.py
python/Ganga/test/GPI/FileTests/TestMassStorageClient.py
python/Ganga/test/GPI/FileTests/TestMassStorageGetPut.py
python/Ganga/test/GPI/FileTests/TestMassStorageInput.py
python/Ganga/test/GPI/FileTests/TestMassStorageWN.py
python/Ganga/test/GPI/Mergers/TestCustomMerger.py
python/Ganga/test/GPI/Mergers/TestMergeFailures.py
python/Ganga/test/Unit/GangaList/TFile/TestTFile.py
python/Ganga/test/Unit/GangaList/TestGangaList.py
python/GangaDirac/Lib/Backends/DiracBase.py
python/GangaDirac/test/GPI/testJobLoading.py

This fixes a bug where on loading a job with a Dirac backend from Ganga 6.2.x in Ganga 6.3.x
This bug crept in between the credentials branch being fixed and the 6.3 release so I've added a test to make sure that this doesn't happen again.
The consequence is any DIRAC job from Ganga 6.2 can't be loaded in 6.3.
(There won't be too many of these as DIRAC lost a lot of sandboxes but users still on Ganga 6.2.x not moving to 6.3 may create new jobs in the future that can't be read in without this fix).
The fix is small in DiracBase and was due to some shortcoming to check for classes in the Schema. The schema is clearly not working correctly in the case of classes as defaults and this should be examined by someone in more detail in a future PR!
This should be working and I think may prompt a …

Fix LHCb job migration

---

python/GangaDirac/Lib/Backends/DiracBase.py
python/GangaDirac/Lib/Files/DiracFile.py

Fixes #910 .
The ```get ``` function got renamed at some point to internalCopyTo, which broke the getOutputData function in DiracBase.
I replaced get in the export methods with the new name.

Replace get with CopyTo

---

python/Ganga/test/GPI/Tasks/TestCoreTasks.py
python/Ganga/testlib/GangaUnitTest.py

This PR moves the tests over to use the user vs session tests. This should help the nightly tests.
If there are no objections I'd like to merge this for 6.3.1 so I can try and debug/fix the nightly tests failing.

Moving to use userConfig to configure test

---

python/Ganga/Core/GangaRepository/VStreamer.py
python/GangaDirac/Lib/Files/DiracFile.py

This should fix #903 whilst improving the exceptions thrown from the XML parser which until now are somewhat cryptic.

Fixing file construction

---

MANIFEST.in

Fixes #920 . Update to include ```.py.template``` files when making the distribution for release.

Update the manifest template

---

python/Ganga/GPIDev/Credentials/VomsProxy.py
python/GangaDirac/Lib/Credentials/DiracProxy.py
python/GangaDirac/Lib/Files/DiracFile.py

Fixes #931 . This takes the `nickname` from the VomsProxy instead of the local username when making the diracLFNBase.
Should clear up problems for people running ganga on local systems with different usernames.

Make diracLFNBase take the username from the DiracProxy

---

python/GangaDirac/Lib/Credentials/DiracProxy.py

This fixes https://github.com/ganga-devs/ganga/issues/883.
The solution is as suggested by @rob-c i.e. just attach a new Shell object. I don't know the implications of this in the wider credentials universe (although it looks fairly innocuous) but it seems to fix the issue for me. Lets see what the tests reveal.

Fix DiracProxy for Vanilla Dirac.

---

python/GangaLHCb/Lib/Backends/__init__.py

Fixes #930. Sets the LHCb plugin to load its own version of Dirac, rather than vanilla.

Change LHCb Backends import to its own Dirac

---

python/GangaLHCb/Lib/Applications/GaudiExecUtils.py

Using `prepareGaudiExec` without a `cmtuser` directory results in a crash due to `makedirs` not being imported (stack trace below).
The following line then uses `chdir` which also isn't imported, however, I don't immediately see why it's needed so I've removed it.
```python
ERROR    Error: global name 'makedirs' is not defined
ERROR    !!Unknown/Unexpected ERROR!!
ERROR    If you're able to reproduce this please report this to the Ganga developers!
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/afs/cern.ch/lhcb/software/releases/GANGA/GANGA_v603r1/install/ganga/python/Ganga/GPI/__init__.py in <module>()
----> 1 execfile('submit.py') …
```

Fix NameError when using prepareGaudiExec

---

python/GangaDirac/Lib/RTHandlers/ExeDiracRTHandler.py
python/GangaDirac/test/Unit/RTHandlers/TestExeDiracRTHandler.py

Fixes #946 
Put the executed command inside a repr so it prints out. Have the raised exception printed out instead of None. Also changed the subprocess.call to work properly.

Fix exception in executable script

---

python/Ganga/Runtime/bootstrap.py
python/Ganga/__init__.py

Fixes #944 . Config option to not need an AFS token when running on AFS.

Add option to not need an AFS token

---

python/GangaLHCb/Lib/RTHandlers/WorkerScript.py.template

Fixes #973 . This now uses an environment variable that is set by the latest LbScripts and points to the default options file for the application.

Update default options path in LHCb RT template

---

python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py
python/GangaLHCb/Lib/Splitters/SplitByFiles.py

Fixes #945 
This adds a check for DiracFiles in the dataset when splitting and not using the Dirac backend. If they are all DiracFiles then it uses the `OfflineGangaDiracSplitter' in order to check for the availability of all the files.
I also found a bug in LHCbDataset  - I wasn't sure of the logic that the code was after but I think this fixes it.

Add DiracSplitter for using DiracFiles locally

---

python/GangaLHCb/Lib/Tasks/LHCbTransform.py

When `files_per_unit <= 0`, `LHCbUnit.input_datset_index` isn't set causing ganga to continuously create new identical units of work.
I've also removed the duplication between the split/unsplit case that (presumably) caused this bug to sneak in.

Fix submission check in LHCbTransform

---

python/GangaDirac/Lib/Splitters/OfflineGangaDiracSplitter.py
python/GangaLHCb/Lib/Splitters/SplitByFiles.py

Fixes #988 . This removes the sites at the site<->SE mapping and removes the LFNs if they end up with no sites or raises an exception if `ignoremissing=False`

Remove banned sites from splitter

---

python/Ganga/GPIDev/Lib/Config/Config.py
python/Ganga/Runtime/bootstrap.py

Fixes #1003 . This just asks for confirmation when copying the gangarc to a new file, both for generating a new gangarc and for version updates.
So far I have used the interactive value which is false for running scripts. Is this the default behaviour we want?

Ask questions when copying the new .gangarc

---

python/Ganga/GPIDev/Lib/Job/Job.py

This fixes a bug reported by Jibo this morning on lhcb-distributed-analysis which was introduced in #996 where I used the wrong config dictionary to access the value of MaxNumResubmits.

Fix accessing key from wrong config

---

python/Ganga/Core/Sandbox/WNSandbox.py
python/Ganga/GPIDev/Lib/File/OutputFileManager.py
python/Ganga/Lib/Localhost/LocalHostExec.py.template
python/GangaAtlas/Lib/ATLASDataset/DQ2Dataset.py
python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/run-athena-new.sh
python/GangaAtlas/PACKAGE.py
python/GangaPanda/PACKAGE.py

This PR adds CMake support into the Atlas plugin. It auto detects this using PandaUtils (which also will need an upgrade) and if it is found, runs a **much** simplified wrapper script on the WN. A later PR will perform clean up of the old code that this supersedes.
In addition, this ensures an Atlas proxy is available when running. This is a 'hacky' fix before I try to get this working properly with the new credential system.
Finally, I found an issue specifically at Cambridge that the code to untar the input sandbox in local and batch jobs was failing on a particular tarball. I've switched the relevant code back to what it was (`extractall()`) and this seems to work.

Add CMake support and Fix minor Credential problem

---

python/GangaLHCb/Lib/Server/DiracLHCbCommands.py

Swapping the default order of protocols round as otherwise, CASTOR sites can have problems. Fixes #1024

Fix order of xroot/root protocols

---

python/Ganga/Runtime/bootstrap.py

Fixes #1045 . 
As an aside would it be better to put the .used_versions file into the home directory? It is kind of annoying to have the gangarc updating when using different gangadirs .

Update gangarc on minor version change

---

python/Ganga/Runtime/bootstrap.py

Bugfix to check that the `~/.cache/Ganga` folder exists at startup.
Could someone please approve this and I'll restart the 6.6.2 release (also the getMetadata PR would be really useful to have in but this one is vital).

Check for existence of cache folder

---

python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/run-athena-new.sh

This PR does the following:
* Adds EXE/ROOT/PYARA support into CMake releases
* Fixes issues with hardcoded architecture path
* Only does compilation if requested
Fixes #1053.
Could this be reviewed ASAP please so it can go out for a tutorial this week? Thanks!

Add EXE support and fix issues with user packages

---

python/Ganga/Core/GangaRepository/Registry.py
python/Ganga/GPIDev/Base/Objects.py
python/Ganga/GPIDev/Lib/Dataset/GangaDataset.py
python/GangaLHCb/Lib/LHCbDataset/LHCbDataset.py

This is a short PR showing some tlc to areas of the code which throw full traces via vanilla ganga and make life difficult for lsst users trying to get used to the framework.
This fixes #1067 that I see when working with LSST people.

Fixing some bad excpetions thrown by Ganga

---

python/Ganga/GPIDev/Lib/File/MassStorageFile.py
python/Ganga/__init__.py
python/Ganga/testlib/GangaUnitTest.py

Fixes #1069 .
Checks that it can make/ls the default MassStoragePath to check the user configs. Also updated the default path for eos to `/usr/bin/eos`

Add config check to MassStorageFile

---

python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/run-athena-new.sh
python/GangaAtlas/scripts/athena

This PR allows users to split Atlas jobs based by event. It's not ideal as the user has to make sure it covers the required number of events but it's not bad for a first go.
Oh, this also removes more Atlas detritus 😄

Enabled event splitting for Atlas local jobs

---

python/GangaAtlas/Lib/ATLASDataset/DQ2Dataset.py
python/GangaAtlas/Lib/Athena/AthenaLocalRTHandler.py
python/GangaAtlas/Lib/Athena/DQ2JobSplitter.py

As Ganga is almost entirely used for local submission in Atlas at the moment and I've been having serious problems getting the proxy stuff working correctly, I've decided to temporarily 'deactivate' the proxy parts in GangaAtlas until I can get a chance to properly fix them. This should allow Ganga to be used efficiently where it's most needed in Atlas.

Temporarily remove proxy stuff for Atlas

---

python/GangaAtlas/Lib/Athena/Athena.py
python/GangaAtlas/PACKAGE.py
python/GangaPanda/PACKAGE.py

This update the version of PandaClient that is shipped with Ganga and also uses the currently set up version if found.

Bump pandatools and check if it's already there

---

python/Ganga/GPIDev/Lib/File/File.py
python/Ganga/GPIDev/Lib/Registry/PrepRegistry.py
python/GangaLHCb/Lib/RTHandlers/GaudiExecRTHandlers.py

This writes the list of `associated_files` from a `ShareDir` to an XML file in the shared directory. This means that if a job is copied and new files added, the original will know about them.
Also added to `GaudiExec` to check the existence of previously uploaded files in case users have been cleaning their grid areas between job submissions.

Save associated_files to xml

---

python/GangaDirac/Lib/Backends/DiracBase.py
python/GangaDirac/Lib/RTHandlers/DiracRTHScript.py.template
python/GangaDirac/__init__.py

Fixes #1129 .
This just puts each submission into the same process. Currently goes from 130s to 23s (of which it looks like 16s are other overheads so only 7s for the subjob submission) for 23 subjobs.
Needs tidying and potentially new script templates although that will also affect RTHandlers.

Speed up Dirac submission

---

python/GangaDirac/Lib/Backends/DiracBase.py
python/GangaDirac/test/Unit/Backends/TestDiracBase.py

Some new code is needed to resubmit Dirac jobs that were initially submitted with bulkSubmit. This still submits them one at a time, but users shouldn't be resubmitting too many.
It takes the original submission scripts and extract the necessary parts.

Fix Dirac bulkSubmit resubmission

---

python/GangaLHCb/Utility/LHCbDIRACenv.py

Currently this is the only platform LHCbDirac is available on. This just allows people to submit jobs with Ganga from any platform.
Note: #1054 has actually been fixed by a change to LbScripts.

Hard-code LHCbDirac platform for gcc49

---

python/Ganga/GPIDev/Adapters/ICredentialInfo.py
python/Ganga/GPIDev/Credentials/CredentialStore.py

Might fix #1141 - certainly fixes a bug that the credential cache doesn't update itself.
I also notice that the renewal command has a time limit of the last hour before expiry otherwise it doesn't do anything. That doesn't make sense to me - a casual user will type `renew()` and assume that the proxy will be valid for the next 24 hours before walking away. Are there any objections to changing that?

Fix credential cache

---

python/GangaDirac/Lib/Backends/DiracBase.py

There is a slight bug in that jobs submitted to DIRAC with old ganga versions cannot be resubmitted with the latest - the `blockSubmit` attribute gets added with the default `true` to these old jobs so it tries to resubmit with the wrong method.
The fix just checks for the existence of the new-style `dirac-script-0.py` to confirm the job was originally submitted with `blockSubmit`, otherwise reverting to the old resubmit code.

DIRAC resubmit bugfix

---

python/GangaAtlas/PACKAGE.py

There was a problem found recently with the panda-client library that Ganga uses in that it wasn't tarring up the user area properly in some cases. This PR bumps the panda-client version to a working version.

Bumped panda-client version

---

requirements.txt

Fixes `py.test` to 3.2.5 so the python2.6 Travis tests can run.

Set py.test version in requirements

---

python/GangaDirac/Lib/Backends/DiracBase.py

User on LHCb dast list reported:
```
ERROR    Exception raised executing 'updateMonitoringInformation' in Thread 'Backend Monitor':
Traceback (most recent call last):
File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.3/python/Ganga/Core/GangaThread/WorkerThreads/WorkerThreadPool.py", line 115, in __worker_thread
result = item.command_input.function(*these_args, **item.command_input.kwargs)
File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.3/python/GangaDirac/Lib/Backends/DiracBase.py", line 1242, in updateMonitoringInformation
DiracBase.monitor_dirac_running_jobs(monitor_jobs_group, finalised_statuses)
File "/cvmfs/ganga.cern.ch/Ganga/install/6.7.3/python/GangaDirac/Lib/Backends/DiracBase.py", line 1204, in monitor_dirac_running_jobs
DiracBase.requeue_dirac_finished_jobs(requeue_job_list, …
```

Fix for race condition

---

python/GangaAtlas/Lib/Athena/Athena.py

Recently, ATLAS have added the AtlasBuildStamp env variable to all setups which makes the check for a nightly fail. This does a proper check for this timestamp format.

Add proper format check for nightly

---

python/Ganga/GPIDev/Lib/Job/Job.py

Fixes #1180 
The removal of the job repository directory needs to be done last, otherwise the subjobs xml list won't find any subjobs.

Reorder job removal
